(function(g){var window=this;var E2=function(a){var b={languageCode:a.i,languageName:a.l,displayName:g.Jz(a),kind:a.o,name:a.u,id:a.Ea,is_servable:a.B,is_default:a.isDefault,is_translateable:a.D,vss_id:a.A};a.g&&(b.translationLanguage=a.g);return b},F2=function(a){return a.g?a.g.languageCode:a.i},kpa=function(a,b){var c=new g.Iz;
c.i=a.i;c.l=a.l;c.u=a.u;c.o=a.o;c.isDefault=!1;c.B=a.B;c.D=a.D;c.A=a.A;c.F=a.F;c.g=b;return c},G2=function(a){if(!lpa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(mpa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},npa=function(){this.i=[];
this.g=[]},H2=function(a,b){return b?a.g.concat(a.i):a.g},I2=function(a,b){switch(b.o){case "asr":var c=a.i;
g.Xa(c,(0,g.y)(b.Lq,b))||c.push(b);break;default:c=a.g,g.Xa(c,(0,g.y)(b.Lq,b))||c.push(b)}},J2=function(){g.H.call(this);
this.i=new npa;this.u=[]},K2=function(a,b,c){J2.call(this,a);
this.g=null;this.u=b.mu;this.l=c},L2=function(){this.Ua=[]},M2=function(a,b,c,d,e,f){g.H.call(this);
this.I=a;this.o=b;this.A=new L2;this.g=null;this.F=d;this.P=f;this.i=this.l=null;this.D=c;this.B=e||!1;this.H=new g.N(this.Cw,1E3,this);g.I(this,this.H);this.u=new g.Ms(this);g.I(this,this.u);g.R(g.X(b).experiments,"html5_disable_captions_seek_complete")?this.u.K(b,"seekto",this.mx):this.u.K(b,"seekcomplete",this.EF);this.mx(b.getCurrentTime());this.Cw()},N2=function(a,b){b-=a.o.ac();
var c=a.g;a.g=g.Ua(a.D.vf(b).g);c!=a.g&&a.P&&a.P()},O2=function(a,b){var c=g.Qv(b,a.I,{}).Gb(),d={format:"RAW",
withCredentials:!0};a.B&&(d.responseType="arraybuffer");a.i=g.wr(c,d,3,100).then((0,g.y)(a.iK,a));a.l=b;c=a.A;d=a.l.g[0].i;var e=g.nb(c.Ua,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.Ua[e-1]&&e<c.Ua.length&&1==c.Ua[e]-d?(g.bb(c.Ua,e),g.bb(c.Ua,e-1)):0<e&&1==d-c.Ua[e-1]?c.Ua[e-1]=d:e<c.Ua.length&&1==c.Ua[e]-d?c.Ua[e]=d:(g.jb(c.Ua,e,0,d),g.jb(c.Ua,e+1,0,d)))},P2=function(a,b){J2.call(this,g.X(b));
this.g=a;this.B=b;this.l=null;this.o=!1;this.A=g.tz(g.X(this.B))&&!this.g.i},Q2=function(a,b){var c=[],d;
for(d in a.g.g){var e=a.g.g[d];if(g.hV(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.Iz({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},opa=function(a,b){return null!=b&&b in a.g.g?a.g.g[b]:null},R2=function(a,b,c){var d=[],e;
for(e in a.g.g){var f=a.g.g[e];if(g.hV(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},S2=function(a,b,c,d,e){J2.call(this,e||null);
c=c||g.Eq(a).hl||"";c=c.split("_").join("-");this.o=g.Gq(a,{hl:c});this.l=b;this.A=!!d;this.B={};this.g=null},T2=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.iE.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.l=f;this.g=k},U2=function(a,b,c,d,e){g.iE.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.g=[]},W2=function(a){a=void 0===a?{}:a;
var b="_"+V2++;return new U2(0,0x8000000000000,0,b,a)},Y2=function(a,b,c,d,e,f){var k={};
g.Ra(k,b);g.Ra(k,a.params);g.Ra(k,c);var l={};g.Ra(l,b.yb);a.params.yb&&g.Ra(l,a.params.yb);g.Ra(l,c.yb);k.yb=l;g.W.call(this,{C:"div",G:"caption-window",L:{id:"caption-window-"+a.id,dir:1==k.xe?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},J:[{C:"span",G:"captions-text",L:{style:"word-wrap: normal; display: block;"}}]});this.B=[];this.O=!1;this.o=a;this.V=this.R=null;this.Ra=e;this.Na=f;this.D=null;this.X=.96*e;this.xa=.96*f;this.l=k;this.La=c;this.A=this.i["captions-text"];this.Ba=
null!=this.A.style["box-decoration-break"]||null!=this.A.style["-webkit-box-decoration-break"];this.Z=d/360*16;this.type=0;this.ka=this.Z*X2(l);a=new g.Ss(this.element,!0);g.I(this,a);a.subscribe("dragstart",this.DF,this);a.subscribe("dragmove",this.CF,this);a.subscribe("dragend",this.BF,this);this.va=this.na=0;b="";this.l.windowOpacity&&(a=G2(this.l.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.l.windowOpacity+")");a={"background-color":b,display:!1===this.l.isVisible?"none":"","text-align":ppa[this.l.textAlign]};
this.Ba&&(a["border-radius"]=b?this.ka/8+"px":"");if(this.u=2==this.o.params.xe||3==this.o.params.xe)b=this.element,c="vertical-rl",1==this.l.oA&&(c="vertical-lr"),g.Ld&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.Ah(b,"-o-writing-mode",c),g.Ah(b,"-webkit-writing-mode",c),g.Ah(b,"writing-mode",c),g.Ah(b,"text-orientation","upright"),g.L(b,"ytp-vertical-caption"),3==this.o.params.xe&&(g.Ah(b,"text-orientation",""),g.Ah(b,"transform","rotate(180deg)"));g.Ah(this.element,a);switch(this.l.Sf){case 0:case 1:case 2:g.L(this.element,
"ytp-caption-window-top");break;case 6:case 7:case 8:g.L(this.element,"ytp-caption-window-bottom")}},X2=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},Z2=function(a,b){var c={},d=b.background?b.background:a.l.yb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.l.yb.backgroundOpacity;d=G2(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ba&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ka/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Z*X2(b)+"px";d=1;e=b.color||a.l.yb.color;if(b.color||null!=b.textOpacity)e=G2(e),d=null==b.textOpacity?a.l.yb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.wu&&(k=e=b.wu);var l=a.Z/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.er()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.l.yb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Ne&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.GD&&(c.visibility="hidden");1==b.ID&&a.u&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.vz||g.wz,3==a.o.params.xe?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1==b.We||2==b.We||3==b.We||4==b.We||5==b.We)c["text-emphasis"]="filled circle",c["webkit-text-emphasis"]="filled circle",g.vz&&(c["font-weight"]="bold");return c},$2=function(a){a.D=g.Rd("SPAN");
g.Ah(a.D,{display:"block"});g.L(a.D,"caption-visual-line");a.A.appendChild(a.D)},a3=function(a,b){var c=g.Rd("SPAN");
g.Ah(c,{display:"inline-block","white-space":"pre-wrap"});g.Ah(c,Z2(a,b));c.classList.add("ytp-caption-segment");a.D.appendChild(c);c.previousElementSibling&&(g.Ah(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Ah(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},b3=function(a,b,c){a.O=a.O||!!c;
var d={};g.Ra(d,a.l.yb);g.Ra(d,c||b.g);g.Ra(d,a.La.yb);(c=!a.D)&&$2(a);for(var e=a.R&&a.V&&g.$b(d,a.V)?a.R:a3(a,d),f=g.v(b.text),k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.l,n=k[l];m&&!c?($2(a),e=a3(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Sd(n):n),f||"RUBY"!=n.tagName||4!=n.childElementCount||g.vz||!g.Eh(n.children[2],"text-emphasis")||(g.Nd?g.Ah(e,"padding-top","1em"):g.Ah(e,"padding-top","0.5em")))}a.V=d;a.R=e;a.B.push(b)},c3=function(){},e3=function(){this.o=this.i=this.mode=
this.l=0;
this.u=new d3(this);this.A=new d3(this);this.g=[];this.clear()},qpa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{xl:a,
yl:b,result:0};a=f3[a];b=f3[b];if(a&128){if(!(b&128)&&0!=c.g&&c.i==b)return{xl:a,yl:b,result:1}}else if(b&128&&1<=a&&31>=a)return{xl:a,yl:b,result:2};return{xl:a,yl:b,result:3}},rpa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.o&&a.reset(),a.u.g.clear(),a.A.g.clear()):(a.o=0,g3(a.u,b,c,d))},spa=function(a,b){a.g.sort(function(e,f){var k=e.time-f.time;
return 0==k?e.order-f.order:k});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.i=d.time;0==d.type?rpa(a,d.pu,d.qu,b):1==d.type&&a.l&496&&g3(a.A,d.pu,d.qu,b)}a.g.length=0},h3=function(){this.g=0},i3=function(){this.i=this.l=this.g=0},j3=function(){this.timestamp=this.Od=0},k3=function(a){this.l=[];
for(var b=0;15>=b;b++){this.l[b]=[];for(var c=0;32>=c;c++)this.l[b][c]=new j3}this.g=this.i=this.row=0;this.style=new h3;this.u=a;this.o=0},l3=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.u.i+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.l[m][p];
if(0!=r.Od){0==c&&(c=m,d=p);n=String.fromCharCode(r.Od);var u=r.timestamp;u<e&&(e=u);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.Od||32==p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.u(c,d,e,l,f)}else for(d=c=0,f=e=a.u.i+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.l[k][m],r=p.Od,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),u=p.timestamp,u<=e&&(e=u),l+=n,p.reset()),32==m||0==r)l&&b.u(c,d,e,f,l),e=f,l="",d=c=0},xpa=function(a,b){switch(a){case 0:return tpa[(b&127)-32];
case 1:return upa[b&15];case 2:return vpa[b&31];case 3:return wpa[b&31]}return 0},m3=function(a){return a.l[a.row][a.i]},n3=function(a,b,c){2<=b&&1<a.i&&(--a.i,m3(a).Od=0);
var d=m3(a);d.timestamp=a.u.i+0;d.Od=xpa(b,c);32>a.i&&a.i++},o3=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.l[b+e][f].ag(a.l[c+e][f])},p3=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.l[b+d][e].reset()},q3=function(a){a.row=0<a.g?a.g:1;
a.i=1;p3(a,0,15)},r3=function(a){this.o=a;
this.u=0;this.style=new h3;this.A=new k3(a);this.B=new k3(a);this.D=new k3(a);this.i=this.A;this.l=this.B;this.g=this.i},s3=function(a,b,c){var d=a.i,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:l3(d,c),q3(a.i),q3(a.l),d.row=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.o.mode=1<<d.o;e?d.i=1:d.g!=b&&(d.g>b?(l3(d,c),p3(d,d.row-d.g,b)):d.row<b&&(b=d.g),d.g=b)},t3=function(a){a.style.set(1);
a.g=a.l;a.g.g=0;a.g.style=a.style;a.o.mode=1<<a.g.o},u3=function(a){a.style.set(4);
a.g=a.D;a.g.style=a.style;a.o.mode=1<<a.g.o},d3=function(a){this.i=a;
this.g=new i3;this.u=0;this.l=new r3(a);this.A=new r3(a);this.o=this.l},g3=function(a,b,c,d){a.g.update();
b=qpa(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.xl;c=b.yl;if(32<=e||!e)a.i.mode&a.i.l&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.o.g,b&96&&n3(a,0,b),c&96&&n3(a,0,c),0!=b&&0!=c&&3==a.style.g&&l3(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.l=e,b.i=c,b.g=2,b=e&8?a.A:a.l,a.o=b,a.i.mode=1<<(a.u<<2)+(b.u<<1)+(4==b.style.g?1:0),(a.i.mode|1<<(a.u<<2)+(b.u<<1)+(4!=b.style.g?1:0))&a.i.l))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.g&&(d=c.g,d==c.row))break;var f=1+c.row-c.g,k=1+d-c.g;o3(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));p3(c,b,e)}}c.row=d;c.i=a+1}else switch(e&7){case 1:switch(c&112){case 32:n3(b.g,0,32);break a;case 48:57==c?(d=b.g,m3(d).Od=0,32>d.i&&d.i++):n3(b.g,1,c&15)}break;case 2:c&32&&n3(b.g,2,c&31);break;case 3:c&32&&n3(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:t3(b);break;case 33:d=
b.g;1<d.i&&(--d.i,m3(d).Od=0);break;case 36:d=b.g;b=m3(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.l[a][c]==b){for(;32>=c;c++)d.l[a][c].reset();break}break;case 37:s3(b,2,d);break;case 38:s3(b,3,d);break;case 39:s3(b,4,d);break;case 40:n3(b.g,0,32);break;case 41:b.style.set(2);b.g=b.i;b.g.g=0;b.g.style=b.style;b.o.mode=1<<b.g.o;break;case 42:d=b.D;d.g=15;d.style.set(4);q3(d);u3(b);break;case 43:u3(b);break;case 44:a=b.i;switch(b.style.get()){case 1:case 2:case 3:l3(a,d)}p3(a,0,15);break;case 45:b:{a=
b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.i=1;break b}case 3:}2>a.g&&(a.g=2,a.row<a.g&&(a.row=a.g));b=a.row-a.g+1;l3(a,d);o3(a,b,b+1,a.g-1);p3(a,a.row,1)}break;case 46:p3(b.l,0,15);break;case 47:l3(b.i,d),b.l.updateTime(b.o.i+0),d=b.l,b.l=b.i,b.i=d,t3(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.g,32<(d.i+=c&3)&&(d.i=32)}}},v3=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1==m.Mf){var n=f[1],p=f[2],r=f[3];l.getAttribute("p");l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");r.getAttribute("t");f=g.Rd("RUBY");l=l.textContent;var u=g.Rd("SPAN");u.innerText=l;f.appendChild(u);n.getAttribute("p");u=g.Rd("RP");l=n.textContent;u.innerText=l;f.appendChild(u);k=k[p.getAttribute("p")];l=p.textContent;p=g.Rd("RT");p.innerText=l;f.appendChild(p);l=k.Mf;if(10==l||11==l||12==l||13==l||14==l)g.Ah(p,"text-emphasis","filled circle"),g.Ah(p,"webkit-text-emphasis","filled circle");
if(4==k.Mf||7==k.Mf)g.Ah(f,"ruby-position","over"),g.Ah(f,"-webkit-ruby-position","before");else if(5==k.Mf||6==k.Mf)g.Ah(f,"ruby-position","under"),g.Ah(f,"-webkit-ruby-position","after");r.getAttribute("p");l=r.textContent;r=g.Rd("RP");r.innerText=l;f.appendChild(r);return new T2(a,b,e,c,f,d,m)}switch(m.Mf){case 9:case 10:m.We=1;break;case 11:m.We=2;break;case 12:m.We=3;break;case 13:m.We=4;break;case 14:m.We=5}return new T2(a,b,e,c,l.textContent||"",d,m)},w3=function(){g.H.apply(this,arguments)},
x3=function(a){w3.call(this);
this.l={};this.F={};this.H={};this.u="_"+V2++;this.A=a;this.D={};this.i=this.g=null;this.B=!0},y3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},z3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},A3=function(a,b){var c=y3(a,b);
return void 0!=c?c:null},C3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return B3.test(c),c},D3=function(a,b){var c={},d=b.getAttribute("ws");
g.Ra(c,d?a.H[d]:a.A);d=A3(b,"mh");null!=d&&(c.Gq=d);d=A3(b,"ju");null!=d&&(c.textAlign=d);d=A3(b,"pd");null!=d&&(c.xe=d);d=A3(b,"sd");null!=d&&(c.oA=d);d=C3(b,"wfc");null!=d&&(c.windowColor=d);d=y3(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},E3=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ra(c,a.F[d]);d=A3(b,"ap");null!=d&&(c.Sf=d);d=y3(b,"cc");null!=d&&(c.Jl=d);d=y3(b,"ah");null!=d&&(c.Oe=d);d=y3(b,"rc");null!=d&&(c.Bk=d);d=y3(b,"av");null!=d&&(c.Dg=d);return c},F3=function(a,b,c,d){var e={};
g.Ra(e,E3(a,b));g.Ra(e,D3(a,b));d?g.$b(e,a.A)?(d=a.u,e=a.A):d="_"+V2++:d=b.getAttribute("id")||"_"+V2++;a=y3(b,"t")+c;b=y3(b,"d")||0x8000000000000;if(2==e.xe||3==e.xe)c=e.Bk,e.Bk=e.Jl,e.Jl=c;return new U2(a,b,0,d,e)},G3=function(a,b,c,d,e,f,k){Y2.call(this,a,b,c,d,e,f,k);
this.type=1},H3=function(a,b,c){this.B=c;
this.version=this.A=this.o=this.g=0;this.i=new DataView(a);this.l=[]},I3=function(a){var b=a.g;
a.g+=1;return a.i.getUint8(b)},J3=function(a){var b=a.g;
a.g+=4;return a.i.getUint32(b)},K3=function(a,b){w3.call(this);
this.i=a;this.track="CC3"==b.l?4:0;this.g=new e3;this.g.l=1<<this.track},M3=function(a){if(g.v(a))return!1;
a=new H3(a,8,0);return L3(a)},L3=function(a){if(!(a.g<a.i.byteLength)||1380139777!=J3(a))return!1;
a.version=I3(a);if(1<a.version)return!1;I3(a);I3(a);I3(a);return!0},N3=function(a,b,c,d,e,f,k){Y2.call(this,a,b,c,d,e,f,k);
g.L(this.element,"ytp-caption-window-rollup");this.type=2;this.F=[];this.I=this.H=this.ca=0;this.M=NaN;this.ya=0;this.Ga=null;this.ia=new g.N(this.nK,433,this);g.I(this,this.ia)},ypa=function(a,b){return(a.u?b.offsetHeight:b.offsetWidth)+1},zpa=function(a){if(isNaN(a.M)){var b=a.l.Jl;
if(b){var c=g.Rd("SPAN");g.ae(c,"\u2013".repeat(b));g.Ah(c,Z2(a,a.l.yb));a.A.appendChild(c);a.M=c.offsetWidth;a.A.removeChild(c)}else a.M=0}return a.M},Apa=function(a,b){if(!b)return"";
a.u&&1!=a.o.params.oA&&(b*=-1);return"translate"+(a.u?"X":"Y")+"("+b+"px)"},O3=function(a){a.F=[].concat(g.ea(document.getElementsByClassName("caption-visual-line")));
for(var b=a.o.params.Bk,c=0,d=0,e=a.F.length-1;c<b&&-1<e;){var f=a.F[e];d+=a.u?f.offsetWidth:f.offsetHeight;c++;e--}a.F.length<b&&(d*=b/a.F.length);a.H=d;a.I=Math.max(zpa(a),a.ya,ypa(a,a.A))},Bpa=function(a,b){O3(a);
var c=a.F.reduce(function(e,f){return(a.u?f.offsetWidth:f.offsetHeight)+e},0);
c=a.H-c;if(c!=a.ca){var d=0<c&&0==a.ca;b||isNaN(c)||d||(g.L(a.element,"ytp-rollup-mode"),g.yo(a.ia));g.Ah(a.A,"transform",Apa(a,c));a.ca=c}O3(a)},P3=function(){w3.call(this)},Q3=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Ne=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3==p.nodeType){p=new T2(b,c,d,e.id,p.nodeValue,f||0<n,g.Wb(l)?void 0:l);m.push(p);var r=e;g.I(r,p);r.g.push(p)}else r={},g.Ra(r,l),Q3(a,b,c,d,e,!0,p,r,m)}},R3=function(a){var b=0;
a=g.q(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+parseFloat(c.value);return 1E3*b},S3=function(a,b,c,d){d=Object.assign({Gq:0},d);
return new U2(a,b,c,"_"+V2++,d)},T3=function(a){g.H.call(this);
this.i=a;this.g=null},W3=function(a){g.UK.call(this,a);
this.u=g.X(a);this.l=a.getVideoData();this.xa=g.rK(a);this.I=a;var b=null,c=g.jp("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Uo(c));this.ba=b;this.o={yb:{}};this.A={yb:{}};this.H=[];this.M={};this.V={};this.P=!1;this.na=g.iV(this.l,this.I);this.ya=!!this.l.captionTracks.length;this.Ba=!!this.l.dj;this.ka="3"==this.u.l;b=a.app.o;c=!(!b||!b.Ok());this.va=!(!b||!b.Bh());this.B=this.ka&&c&&!this.na;this.R=!this.B&&this.ka&&this.va&&this.na;this.i=this.D=this.F=this.O=this.ia=null;this.Z=
new T3(this.u);g.I(this,this.Z);c=b=this.g=null;this.B||(b=new g.vo(this.EA,void 0,this),g.I(this,b),c=new g.N(this.JL,2E3,this),g.I(this,c));this.X=b;this.ca=c;this.aa=new g.Ms(this);g.I(this,this.aa);this.B||this.aa.K(a,"resize",this.Ks);this.aa.K(a,"onPlaybackAudioChange",this.MH);this.aa.K(a,g.lE("captions"),this.NE,this);this.aa.K(a,"crx_captions",this.OE,this);U3(this,V3(this,"display-settings")||{})},X3=function(a){if(1==a.u.Wf||1==a.l.Wf||"alwayson"==g.NB(a.l,"yt:cc"))return!0;
if(2==a.u.Wf){var b=V3(a,"module-enabled");if(null!=b)return!!b}if(a.l.captionTracks.length)var c=a.player.getAudioTrack().So;return"ON"==c||"on"==g.NB(a.l,"yt:cc")},Y3=function(a,b){if(a.g&&(void 0===b||!b)||!a.l.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.Sl||"FORCED_ON"==c.So},$3=function(a,b){if(a.i){if(a.D&&a.D.g)return a.D.g;
var c=b;c||(c=a.Ba?!1:a.ya?!1:!0);c=H2(a.i.i,c);for(var d=[a.l.Vf,a.u.Vf,g.NB(a.l,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(F2(c[f])==d[e])return c[f];return a.D&&a.D.ip?a.D.ip:(d=c.find(function(k){return k.isDefault}))?d:c[0]||Z3(a)}return null},Z3=function(a){return a.D&&a.D.Sl},a4=function(a){var b=Z3(a);
return!!b&&a.g==b},b4=function(a,b){for(var c=a.I.app.o.ha().textTracks,d=a.g.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},d4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.P=c,a.P&&c4(a,"module-enabled",!!b));a.g=b;Y3(a)&&(a.g=Z3(a));a.load()},Cpa=function(a,b){var c=a.xa.getVideoContentRect(!0).height;
if(!c)return null;var d=a.xa.getPlayerSize();switch(null!=b.params.Gq?b.params.Gq:1<b.g.length?1:0){case 1:return new G3(b,a.o,a.A,c,d.width,d.height,a.u.experiments);case 2:return new N3(b,a.o,a.A,c,d.width,d.height,a.u.experiments);default:return new Y2(b,a.o,a.A,c,d.width,d.height,a.u.experiments)}},U3=function(a,b,c){var d=e4.yb;
a.o={};g.Ra(a.o,e4);a.o.yb={};g.Ra(a.o.yb,d);a.A={yb:{}};var e=b.backgroundOverride?a.A:a.o,f=b.background||d.background;B3.test(f);e.yb.background=f;e=b.colorOverride?a.A:a.o;f=b.color||d.color;B3.test(f);e.yb.color=f;e=b.windowColorOverride?a.A:a.o;f=b.windowColor||e4.windowColor;B3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.A:a.o;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.yb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.A:a.o;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.yb.fontSizeIncrement=f;f=b.fontStyleOverride?a.A:a.o;e=b.fontStyle;null==e&&(e=d.bold&&d.Ne?3:d.bold?1:d.Ne?2:0);f=f.yb;switch(e){case 1:f.bold=!0;delete f.Ne;break;case 2:delete f.bold;f.Ne=!0;break;case 3:f.bold=!0;f.Ne=!0;break;default:delete f.bold,delete f.Ne}e=b.textOpacityOverride?a.A:a.o;f=b.textOpacity;null==f&&(f=d.textOpacity);e.yb.textOpacity=f;e=b.windowOpacityOverride?a.A:a.o;f=b.windowOpacity;null==f&&(f=e4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.A:a.o;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.yb.charEdgeStyle=f;e=b.fontFamilyOverride?a.A:a.o;f=b.fontFamily;null==f&&(f=d.fontFamily);e.yb.fontFamily=f;a.loaded&&a.Ks();c&&c4(a,"display-settings",b)},g4=function(a,b){if(b&&!a.F){var c=W2({xe:0,
lang:"en"});a.F=[c,new T2(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.zK(a.player,a.F)}else!b&&a.F&&(f4(a,a.F),a.F=null)},f4=function(a,b){g.BK(a.player,b);
(0,g.B)(b,function(c){g.cb(this.H,c)},a);
a.X.Cj()},V3=function(a,b){if(!a.ba)return null;
try{var c=a.ba.get(b)}catch(d){a.ba.remove(b)}return c},c4=function(a,b,c){if(a.ba)try{a.ba.set(b,c)}catch(d){}};
g.vC.prototype.fj=g.ca(13,function(){for(var a=g.Ed(document,"track",void 0,this.g),b=0;b<a.length;b++)g.Wd(a[b])});
g.ZW.prototype.fj=g.ca(12,function(){this.g.fj()});
g.vC.prototype.Ok=g.ca(11,function(){return!!this.g.textTracks});
g.ZW.prototype.Ok=g.ca(10,function(){return this.g.Ok()});
g.vC.prototype.Yi=g.ca(9,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.ZW.prototype.Yi=g.ca(8,function(a){this.g.Yi(a)});
g.mC.prototype.Bh=g.ca(7,function(){});
g.vC.prototype.Bh=g.ca(6,function(){return!(!this.g.textTracks||!this.g.textTracks.addEventListener)});
g.ZW.prototype.Bh=g.ca(5,function(){return this.g.Bh()});
g.Iz.prototype.Lq=g.ca(3,function(a){return a?this.toString()==a.toString():!1});
g.Ht.prototype.fm=g.ca(2,function(a){return(a=this.eg(a))?a.i:0});
g.Bw.prototype.fm=g.ca(1,function(){return 0});
var Dpa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,mpa=/#(.)(.)(.)/,lpa=/^#(?:[0-9a-f]{3}){1,2}$/i,B3=/^#(?:[0-9a-f]{3}){1,2}$/i;g.t(J2,g.H);J2.prototype.iz=function(){return!1};
J2.prototype.T=function(){this.Eg();g.H.prototype.T.call(this)};
g.t(K2,J2);K2.prototype.Dq=function(a,b,c){b=this.yj(a,b);var d=(0,g.y)(function(e){this.g=null;c(e.responseText,a)},this);
this.Eg();this.g=g.Xq(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
K2.prototype.Eq=function(a){if(this.l)for(var b=g.q(this.l.captionTracks),c=b.next();!c.done;c=b.next())I2(this.i,c.value);a()};
K2.prototype.yj=function(a,b){var c=a.Gb(),d={fmt:b};a.g&&(d.tlang=F2(a));return g.Gq(c,d)};
K2.prototype.Eg=function(){this.g&&this.g.abort()};
L2.prototype.contains=function(a){a=g.nb(this.Ua,a);return 0<=a||0>a&&1==(-a-1)%2};
L2.prototype.length=function(){return this.Ua.length/2};
g.t(M2,g.H);g.h=M2.prototype;g.h.T=function(){g.H.prototype.T.call(this);this.i&&this.i.cancel()};
g.h.mx=function(a){var b=this;if(this.D.di())var c=this.u.K(this.o,"progresssync",function(){b.D.index.Eb()&&(b.reset(),b.g=null,N2(b,b.o.getCurrentTime()),b.u.Ma(c))});
else N2(this,a)};
g.h.EF=function(){N2(this,this.o.getCurrentTime())};
g.h.reset=function(){this.A=new L2;this.i&&(this.i.cancel(),this.i=null)};
g.h.Cw=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.Ff(a);!a||this.i||this.g&&30<this.g.startTime-this.o.getCurrentTime()||(a=this.g,a=a.g.mi(a),a.g[0].duration&&(this.A.contains(a.g[0].i)||O2(this,a),this.g=g.Ua(a.g)));this.H.start()};
g.h.iK=function(a){var b=!(this.B?a.response:a.responseText)||400<=a.status,c=g.Iw(a);c?(a=g.Qv(this.l,this.I,{}),b=this.l,g.Lv(b.i,a,c),b.requestId=a.get("req_id"),O2(this,this.l)):(b||null===this.F||(this.B?this.F(a.response,1E3*(this.l.g[0].startTime+this.o.ac())):this.F(a.responseText,1E3*(this.l.g[0].startTime+this.o.ac()))),this.i=this.l=null)};
g.t(P2,J2);g.h=P2.prototype;g.h.Dq=function(a,b,c){this.Eg();b=opa(this,a.getId());b||(b=a.i,b=this.g.i?R2(this,b,"386"):R2(this,b));if(b){var d=1E3*(b.index.fm(b.index.me())-b.index.Ic(b.index.me()));this.l=new M2(new g.gv,this.B,b,function(e,f){c(e,a,f,d)},this.A||g.$u(b.info),(0,g.y)(function(){this.l&&this.l.reset();
this.o=!0},this))}};
g.h.iz=function(){var a=this.o;this.o=!1;return a};
g.h.Eq=function(a){var b;this.A?b=[new g.Iz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Iz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.g.i?Q2(this,"386"):Q2(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())I2(this.i,c.value);a()};
g.h.Eg=function(){this.l&&(this.l.dispose(),this.l=null)};
g.h.yj=function(){return""};
g.t(S2,J2);S2.prototype.Dq=function(a,b,c){b=this.yj(a,b);var d=(0,g.y)(function(e){this.g=null;c(e.responseText,a)},this);
this.Eg();this.g=g.Xq(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
S2.prototype.Eq=function(a){var b=this.o,c={type:"list",tlangs:1,v:this.l,vssids:1};this.A&&(c.asrs=1);b=g.Gq(b,c);c=(0,g.y)(function(d){this.g=null;if((d=d.responseXML)&&d.firstChild){for(var e=g.q(d.getElementsByTagName("track")),f=e.next();!f.done;f=e.next()){var k=f.value;f=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),p=k.getAttribute("id"),r="true"==k.getAttribute("lang_default"),u="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
I2(this.i,new g.Iz({languageCode:f,languageName:l,name:m,kind:n,id:p,is_servable:!0,is_translateable:u,vss_id:k,is_default:r}))}d=d.getElementsByTagName("target");e=d.length;for(f=0;f<e;f++)l=d[f].getAttribute("lang_code"),m=d[f].getAttribute("lang_translated"),n=d[f].getAttribute("lang_original"),p=d[f].getAttribute("id"),r="true"==d[f].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:p,isDefault:r},this.B[l.languageCode]=l.languageName,this.u.push(l)}a()},this);
this.Eg();this.g=g.Xq(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
S2.prototype.yj=function(a,b){var c=this.o,d={v:this.l,type:"track",lang:a.i,name:a.getName(),kind:a.o,fmt:b};a.g&&(d.tlang=F2(a));return c=g.Gq(c,d)};
S2.prototype.Eg=function(){this.g&&this.g.abort()};var ppa=["left","right","center","justify"];var e4={windowColor:"#080808",windowOpacity:0,textAlign:2,Sf:7,Oe:50,Dg:100,yb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.t(T2,g.iE);T2.prototype.toString=function(){return g.iE.prototype.toString.call(this)};g.t(U2,g.iE);U2.prototype.toString=function(){return g.iE.prototype.toString.call(this)};
var V2=0;g.t(Y2,g.W);g.h=Y2.prototype;g.h.DF=function(a,b){var c=g.Qh(this.element,this.element.parentElement);this.na=a-c.x;this.va=b-c.y;g.L(this.element,"ytp-dragging")};
g.h.CF=function(a,b){var c=g.Uh(this.element),d=a-this.na-.02*this.Ra,e=b-this.va-.02*this.Na,f=(d+c.width/2)/this.X*3;f=Math.floor(g.od(f,0,2));var k=(e+c.height/2)/this.xa*3;k=Math.floor(g.od(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.X;d=100*g.od(d,0,1);c=(e+k/2*c.height)/this.xa;c=100*g.od(c,0,1);this.o.params.Sf=l;this.o.params.Dg=c;this.o.params.Oe=d;this.l.Sf=l;this.l.Dg=c;this.l.Oe=d;this.Gz()};
g.h.BF=function(){g.lo(this.element,"ytp-dragging")};
g.h.Gz=function(){this.yh(this.B)};
g.h.yh=function(a){var b=Math.min(this.Bv(),this.X),c=this.Av(),d="";3==this.o.params.xe&&(d="rotate(180deg)");g.Ah(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Go(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.l.Oe+2;d=this.l.Sf;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.A.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.l.Dg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.Ah(this.element,a)};
g.h.Go=function(a){var b;for(b=0;b<a.length&&a[b]==this.B[b];b++);if(this.O||this.B.length>b)b=0,this.O=!1,this.B=[],this.D=this.V=this.R=null,g.Ud(this.A);for(;b<a.length;b++)b3(this,a[b])};
g.h.Bv=function(){return 0};
g.h.Av=function(){return 0};
g.h.toString=function(){return g.W.prototype.toString.call(this)};c3.prototype.u=function(){};e3.prototype.clear=function(){this.o=this.i=this.mode=0;this.g=[];this.reset()};
e3.prototype.reset=function(){this.mode=0;this.u.reset(0);this.A.reset(1)};
var f3=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];h3.prototype.set=function(a){this.g=a};
h3.prototype.get=function(){return this.g};
i3.prototype.clear=function(){this.g=0};
i3.prototype.update=function(){this.g=2==this.g?1:0};
i3.prototype.matches=function(a,b){return 0!=this.g&&a==this.l&&b==this.i};
j3.prototype.ag=function(a){this.Od=a.Od;this.timestamp=a.timestamp};
j3.prototype.reset=function(){this.timestamp=this.Od=0};
k3.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.l[b][c].timestamp=a};
k3.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.l[b][c];a=0==d.Od?a+"_":a+String.fromCharCode(d.Od)}a+="\n"}return a};
k3.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.l[b][c].reset();this.o=a;this.g=0;this.i=this.row=1};
var tpa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],upa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],vpa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],wpa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];r3.prototype.reset=function(a,b){this.u=b;this.style.set(2);this.i=this.A;this.l=this.B;this.g=this.i;var c=(a<<2)+(b<<1);this.A.reset(c);this.B.reset(c);this.D.reset((a<<2)+(b<<1)+1)};
d3.prototype.reset=function(a){this.u=a;this.g.clear();this.o=this.l;this.l.reset(a,0);this.A.reset(a,1)};g.t(w3,g.H);w3.prototype.reset=function(){};g.t(x3,w3);x3.prototype.reset=function(){this.D={};this.i=this.g=null;this.B=!0};
x3.prototype.o=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.l,l={},m=c.getAttribute("p");m&&g.Ra(l,this.l[m]);m=z3(c,"b");null!=m&&(l.bold=
m);m=z3(c,"i");null!=m&&(l.Ne=m);m=z3(c,"u");null!=m&&(l.underline=m);m=A3(c,"et");null!=m&&(l.charEdgeStyle=m);m=A3(c,"of");null!=m&&(l.offset=m);m=C3(c,"bc");null!=m&&(l.background=m);m=C3(c,"ec");null!=m&&(l.wu=m);m=C3(c,"fc");null!=m&&(l.color=m);m=A3(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=y3(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=y3(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=y3(c,"fo");void 0!=m&&(l.textOpacity=m/255);m=A3(c,"rb");null!=m&&10!=m&&(l.Mf=10<m?m-1:m);m=A3(c,
"hg");null!=m&&(l.ID=m);c=A3(c,"te");null!=c&&(2==c&&(l.bold=!1,c=1),l.We=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.H[d]=D3(this,c);break;case "wp":d=c.getAttribute("id"),this.F[d]=E3(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.g=F3(this,d,e,!1);g.I(this,this.g);(d=this.D[this.g.id])&&d.end>this.g.start&&(d.end=this.g.start);this.D[this.g.id]=this.g;c.push(this.g);break;case "p":var n=
e;k=[];l=d.getAttribute("w")||this.u;m=!!z3(d,"a");n=(y3(d,"t")||0)+n;var p=y3(d,"d")||5E3;m||(!this.B&&this.i&&this.i.windowId==l&&this.i.end>n&&(this.i.end=n),this.i&&"\n"==this.i.text&&(this.i.text=""));var r=m?6:5,u=this.l[d.getAttribute("p")],z=[].concat(g.ea(d.childNodes));z.length&&(this.B=null!=d.getAttribute("d"));for(var C=0;C<z.length;C++){var E=z[C];0<C&&(m=!0);var F=void 0;1==E.nodeType&&(F=E);if(F&&"s"==F.tagName)if((E=this.l[F.getAttribute("p")])&&E.Mf)1==E.Mf?(F=v3(n,p,l,m,r,z.slice(C,
C+4),this.l),C+=3):F=v3(n,p,l,m,r,[F],this.l);else{var K=F;F=n;E=p;var Z=l,Ia=m,na=r,Va=K.textContent?K.textContent:"",ve=this.l[K.getAttribute("p")];K=y3(K,"t")||0;F=new T2(F+K,E-K,na,Z,Va,Ia,ve)}else F=new T2(n,p,r,l,E.textContent||"",m,u);k.push(F);this.i=F}if(0<k.length)for(k[0].windowId==this.u&&(this.g=F3(this,d,e,!0),g.I(this,this.g),c.push(this.g)),d=g.q(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.g.id,l=this.g,g.I(l,k),l.g.push(k),c.push(k)}e=c}else e=[];return e};g.t(G3,Y2);G3.prototype.Go=function(a){var b=this.o.g;Y2.prototype.Go.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.g==e)var d=f;else{d={};g.Ra(d,c.g);g.Ra(d,Epa);var e=c.g;var f=d}b3(this,c,d)}};
var Epa={GD:!0};g.t(H3,c3);H3.prototype.u=function(a,b,c,d,e){if(c<d){var f="_"+V2++;c=c/1E3-this.B;d=d/1E3-this.B;a=new U2(c,d-c,5,f,{textAlign:0,Sf:0,Oe:2.5*b,Dg:5.33*a});e=new T2(c,d-c,5,f,e);this.l.push(a);this.l.push(e)}};
g.t(K3,w3);K3.prototype.o=function(a){a=new H3(a,a.byteLength,this.i);if(L3(a)){for(;a.g<a.i.byteLength;)for(0==a.version?a.o=J3(a)*(1E3/45):1==a.version&&(a.o=4294967296*J3(a)+J3(a)),a.A=I3(a);0<a.A;a.A--){var b=I3(a),c=I3(a),d=I3(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.g,b.g.push({time:a.o,type:this.track,pu:c,qu:d,order:b.g.length}))}spa(this.g,a);return a.l}return[]};
K3.prototype.reset=function(){this.g.clear()};g.t(N3,Y2);g.h=N3.prototype;g.h.Gz=function(){g.zo(this.ia)};
g.h.nK=function(){g.lo(this.element,"ytp-rollup-mode");this.yh(this.Ga,!0)};
g.h.Av=function(){return this.u?this.I:this.H};
g.h.Bv=function(){return this.u?this.H:this.I};
g.h.yh=function(a,b){this.Ga=a;if(this.o.params.Bk){for(var c=0,d=0;d<this.B.length&&c<a.length;d++)this.B[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.B.concat(a.slice(c)));this.ya=this.I;this.H=this.I=0;Y2.prototype.yh.call(this,a);Bpa(this,b);Y2.prototype.yh.call(this,a)}else Y2.prototype.yh.call(this,a)};g.t(P3,w3);
P3.prototype.o=function(a,b){for(var c=[],d=a.split(Fpa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!Gpa.test(f)){var l=h4.exec(f);if(l&&4<=l.length){var m=R3(l[1]),n=R3(l[2])-m;m+=k;var p,r=p=void 0,u=void 0,z=void 0,C=l[3];l={textAlign:2};C=g.q(C?C.split(" "):[]);for(var E=C.next();!E.done;E=C.next())if(E=E.value.split(":"),2==E.length){var F=E[1];switch(E[0]){case "line":E=F.split(",");E[0].endsWith("%")&&(z=E[0],l.Dg=Number.parseInt(z,10),2==E.length&&(u=E[1].trim()));break;case "position":E=F.split(",");
r=E[0];l.Oe=Number.parseInt(r,10);2==E.length&&(p=E[1].trim());break;case "align":switch(F){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}z||(l.Dg=100,u||(u="end"));if(!r)switch(l.textAlign){case 0:l.Oe=0;break;case 1:l.Oe=100;break;default:l.Oe=50}r=0;switch(u){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(p){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.Sf=0>r||8<r?7:r;p=l;f=f.substring(h4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");r=p;p=f;f={};if(0>p.indexOf("<")&&0>p.indexOf("&"))k=S3(m,n,5,r),n=new T2(m,n,5,k.id,p,!1,g.Wb(f)?void 0:f),c.push(k),c.push(n),g.I(k,n),k.g.push(n);else for(u=p.split(Hpa),1==u.length?(p=5,r=S3(m,n,p,r)):(z=p=6,r=Object.assign({Jl:32},r),r=new U2(m,n,z,"_"+V2++,r)),c.push(r),z=m,l=0;l<u.length;l++)C=u[l],0==l%2?(E=g.no("<html>"+C+"</html>"),E.getElementsByTagName("parsererror").length?
(F=E.createElement("span"),F.appendChild(E.createTextNode(C))):F=E.firstChild,Q3(this,z,n-(z-m),p,r,0<l,F,f,c)):z=R3(C)+k}h4.lastIndex=0}}return c};
var Gpa=/^NOTE/,Fpa=/(?:\r\n|\r|\n){2,}/,h4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Hpa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.t(T3,g.H);T3.prototype.clear=function(){this.g&&this.g.dispose();this.g=null};
T3.prototype.reset=function(){this.g&&this.g.reset()};
T3.prototype.T=function(){this.clear();g.H.prototype.T.call(this)};g.t(W3,g.UK);g.h=W3.prototype;g.h.T=function(){if(this.B||this.R){var a=this.I.app.o;a&&a.fj()}else g4(this,!1);g.UK.prototype.T.call(this)};
g.h.Gk=function(){return this.ka?this.B||this.R:Y3(this)?!0:X3(this)};
g.h.load=function(){g.UK.prototype.load.call(this);this.D=this.player.getAudioTrack();if(this.i)this.g&&(this.Z.clear(),this.B?b4(this,!0):3!=this.player.getPresentingPlayerType()&&this.i.Dq(this.g,"srv3",(0,g.y)(this.UK,this))),this.g&&!a4(this)?this.player.ma("captionschanged",E2(this.g)):this.player.ma("onCaptionsTrackListChanged");else{var a;this.na?a=new P2(this.l.ga,this.player):this.ya?a=new K2(this.u,this.l,this.player.getAudioTrack()):a=new S2(this.l.dj,this.l.videoId,this.l.Vf||this.u.Vf||
g.NB(this.l,"yt:cc_default_lang")||this.u.Wb,this.l.Qo,this.u);this.i=a;g.I(this,this.i);a.Eq((0,g.y)(this.TK,this))}};
g.h.unload=function(){this.B&&this.g?b4(this,!1):(this.ca&&g.Ao(this.ca),g.CK(this.player,"captions"),this.H=[],this.i&&this.i.Eg(),this.Z.clear(),this.F&&g.zK(this.player,this.F),this.Ks());g.UK.prototype.unload.call(this);var a=g.V(this.player.app);a&&a.o&&g.xD(a.o.l);this.player.ma("captionschanged",{})};
g.h.TK=function(){var a;this.P||X3(this)?a=$3(this,this.P):Y3(this)&&(a=Z3(this));if(this.B||this.R){for(var b=H2(this.i.i,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.Jz(e),srclang:F2(e),id:e.toString()};this.R||(f.src=this.i.yj(e,"vtt"));e==a&&(f["default"]=1);c.push(g.Qd("TRACK",f))}this.I.app.o.Yi(c);a=this.I.app.o.ha();this.va&&this.aa.K(a.textTracks,"change",this.VK)}else!this.g&&a&&d4(this,a),this.player.ma("onCaptionsTrackListChanged"),this.player.ma("onApiChange")};
g.h.VK=function(){for(var a=this.I.app.o.ha().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=H2(this.i.i,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.g:null)!=b&&d4(this,b,!0)};
g.h.qM=function(){!this.g&&this.B||this.unload()};
g.h.UK=function(a,b,c,d){if(a){this.i.iz()&&(this.H=[],g.CK(this.I,"captions"),this.X.Cj(),this.Z.reset());var e=this.Z;c=c||0;d=d||0;if(!g.v(a)){var f=new DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.au(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!M3(a))){a=new Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&63)}else if(239<m&&365>m){n=
a[k++];var p=a[k++],r=a[k++];m=((m&7)<<18|(n&63)<<12|(p&63)<<6|r&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],p=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|p&63)}a=f.join("")}}if(a)try{if(g.v(a)){if("WEBVTT"==a.substring(0,6)){b=a;var u=c;e.g||(e.g=new P3);var z=e.g.o(b,u);.01>Math.random()&&g.Vp(Error("Deprecated subtitles format in web player: WebVTT"));var C=z}else b:{z=a;u=g.no(z);if(!u||!u.firstChild){var E=Error("Invalid caption track data");
E.params=z;throw E;}if("timedtext"==u.firstChild.tagName){if(3==parseInt(u.firstChild.getAttribute("format"),10)){if(!e.g){z={};var F=F2(b);F&&(z.lang=F,Dpa.test(F)&&(z.xe=1));e.g=new x3(z,e.i)}C=e.g.o(u,c);break b}var K=Error("Unsupported subtitles format in web player (Format2)");K.params=z;throw K;}if("transcript"==u.firstChild.tagName){var Z=Error("Unsupported subtitles format in web player (Format1)");Z.params=z;throw Z;}var Ia=Error("Invalid caption track data");Ia.params=z;throw Ia;}var na=
C}else{C=a;u=c;F=d;if(!M3(C))throw Error("Invalid binary caption track data");e.g||(e.g=new K3(F,b));na=e.g.o(C,u)}var Va=na}catch(ve){g.O(ve),e.clear(),Va=[]}else Va=[];g.zK(this.player,Va);!this.P||this.R||a4(this)||g.jz(this.u)||g.kz(this.u)||(g.Ao(this.ca),Va=W2({Sf:0,Oe:5,Dg:5,Bk:2,textAlign:0,xe:0,lang:"en"}),this.O=[Va],e=["Click "," for settings"],this.ia||(na=new g.ZC(g.aQ()),g.I(this,na),this.ia=na.element),na=Va.end-Va.start,(b=g.Jz(this.g))&&this.O.push(new T2(Va.start,na,0,Va.id,b)),
this.O.push(new T2(Va.start,na,0,Va.id,e[0]),new T2(Va.start,na,0,Va.id,this.ia,!0),new T2(Va.start,na,0,Va.id,e[1],!0)),g.zK(this.player,this.O),g.yo(this.ca));!this.P||this.R||a4(this)||(c4(this,"module-enabled",!0),this.D&&(this.D.g=this.g),(Va=g.V(this.player.app))&&Va.o&&g.xD(Va.o.l));this.P=!1}};
g.h.NE=function(a){this.H.push(a);this.X.Cj()};
g.h.OE=function(a){g.cb(this.H,a);this.i instanceof P2&&this.i.A&&g.BK(this.player,[a]);this.X.Cj()};
g.h.DL=function(a){if(a instanceof U2){var b=this.M[a.id];b&&b.o!=a&&(b.dispose(),delete this.M[a.id],b=null);b||(b=Cpa(this,a))&&(this.M[a.id]=b)}else b=a.windowId,this.V[b]||(this.V[b]=[]),this.V[b].push(a)};
g.h.JL=function(){f4(this,this.O);this.O=null};
g.h.EA=function(){this.X.stop();g.Xb(this.V);this.H.sort(g.kE);var a=this.H;if(this.F){var b=(0,g.Xd)(a,function(c){return-1==this.F.indexOf(c)},this);
b.length&&(a=b)}(0,g.B)(a,this.DL,this);g.Jb(this.M,function(c,d){this.V[d]?(c.element.parentNode||g.GK(this.player,c.element,4),c.yh(this.V[d])):(c.dispose(),delete this.M[d])},this)};
g.h.NL=function(){U3(this,{},!0)};
g.h.VC=function(){var a=e4.yb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Ne?3:a.bold?1:a.Ne?2:0,textOpacity:a.textOpacity,windowColor:e4.windowColor,windowOpacity:e4.windowOpacity};var b=V3(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.JA=function(a,b){var c={};g.Ra(c,V3(this,"display-settings"));g.Ra(c,a);U3(this,c,b);this.player.N("captionssettingschanged")};
g.h.Ks=function(){!this.B&&this.loaded&&(g.Jb(this.M,function(a,b){a.dispose();delete this.M[b]},this),this.EA())};
g.h.Zb=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.od(b,-2,4);this.JA({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&d4(this,this.g,!0);break;case "stickyLoading":void 0!=b&&this.u.ub&&c4(this,"module-enabled",!!b);break;case "track":if(!this.i)return{};if(b){if(this.B)break;if(!g.Na(b))break;if(g.Wb(b)){d4(this,null,!0);break}for(var d=H2(this.i.i,!0),e=0;e<d.length;e++){var f=d[e];f.i!=b.languageCode||c&&f.l!=b.languageName||(c=b.translationLanguage?kpa(f,b.translationLanguage):
f)}!c||c==this.g&&this.loaded||d4(this,c,!0)}else return this.loaded&&this.g&&!a4(this)?E2(this.g):{};return"";case "tracklist":return this.i?(0,g.G)(H2(this.i.i,!(!b||!b.includeAsr)),function(k){return E2(k)}):[];
case "translationLanguages":return this.i?this.i.u:[];case "sampleSubtitles":this.B||void 0==b||g4(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.u.ub&&a.push("stickyLoading");return a};
g.h.Aj=function(){var a=this.g;return a?{cc:a.A}:{}};
g.h.uA=function(){this.loaded&&this.g&&!a4(this)?(c4(this,"module-enabled",!1),this.unload(),Y3(this,!0)&&d4(this,Z3(this),!1)):d4(this,a4(this)||!this.g?$3(this,!0):this.g,!0)};
g.h.MH=function(){var a=a4(this);Y3(this,a)?d4(this,this.player.getAudioTrack().Sl,!1):this.l.captionTracks.length&&(this.loaded&&this.unload(),this.Gk()&&(a?d4(this,$3(this),!1):this.load()))};g.oV.captions=W3;})(_yt_player);
