(function(g){var window=this;var i4=function(a,b,c){var d=b.oa();g.M(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.yc(c?c:"mqdefault.jpg");var f=b instanceof g.kB&&b.lengthSeconds?g.WQ(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.mE(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.kB?b.ra:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.Zi||g.EN("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.Bj(),is_live:l,is_list:k,
is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.oE&&(d.playlist_length=b.getLength());a.update(d)},j4=function(a,b){g.dD.call(this,{C:"div",
W:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},k4=function(a){g.W.call(this,{C:"div",
W:["ytp-upnext","ytp-player-content"],L:{"aria-label":"{{aria_label}}"},J:[{C:"div",G:"ytp-cued-thumbnail-overlay-image",L:{style:"{{background}}"}},{C:"span",G:"ytp-upnext-top",J:[{C:"span",G:"ytp-upnext-header",U:"Up Next"},{C:"span",G:"ytp-upnext-title",U:"{{title}}"},{C:"span",G:"ytp-upnext-author",U:"{{author}}"}]},{C:"a",G:"ytp-upnext-autoplay-icon",L:{role:"button",href:"{{url}}","aria-label":"Play next video"},J:[{C:"svg",L:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},J:[{C:"circle",
G:"ytp-svg-autoplay-circle",L:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{C:"circle",G:"ytp-svg-autoplay-ring",L:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{C:"path",G:"ytp-svg-fill",L:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{C:"span",G:"ytp-upnext-bottom",J:[{C:"span",G:"ytp-upnext-cancel"},{C:"span",G:"ytp-upnext-paused",U:"Autoplay is paused"}]}]});
this.A=null;var b=this.i["ytp-upnext-cancel"];this.A=new g.W({C:"button",W:["ytp-upnext-cancel-button","ytp-button"],L:{tabindex:"0","aria-label":"Cancel autoplay"},U:"Cancel"});g.I(this,this.A);this.A.da("click",this.RH,this);this.A.g(b);this.l=a;this.I=this.i["ytp-svg-autoplay-ring"];this.D=this.B=this.o=this.u=null;this.F=new g.N(this.Il,5E3,this);g.I(this,this.F);this.H=0;this.K(this.i["ytp-upnext-autoplay-icon"],"click",this.GJ);this.jy();this.K(a,"autonavvisibility",this.jy);this.K(a,"mdxnowautoplaying",
this.VI);this.K(a,"mdxautoplaycanceled",this.WI);this.K(a,"mdxautoplayupnext",this.IA);3==this.l.getPresentingPlayerType()&&(a=(a=g.sK(g.mK(this.l)))?a.TC():null)&&this.IA(a)},l4=function(a,b){if(!a.o){g.jq("a11y-announce","Up Next "+a.u.title);
a.H=g.P();a.o=new g.N((0,g.y)(a.Fo,a,b),25);a.Fo(b);var c=b||g.S(g.X(a.l).experiments,"autoplay_time")||1E4;a.l.ma("onAutonavCoundownStarted",c)}g.lo(a.element,"ytp-upnext-autoplay-paused")},n4=function(a){m4(a);
a.H=g.P();a.Fo();g.L(a.element,"ytp-upnext-autoplay-paused")},m4=function(a){a.o&&(a.o.dispose(),a.o=null)},o4=function(a,b){b=void 0===b?!1:b;
if(g.R(g.X(a.l).experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.u.oa(),a.Il(),a.B=new Notification("Up Next",{body:c.title,icon:c.yc()}),a.D=a.K(a.B,"click",a.yJ),a.F.start())}m4(a);a.l.nextVideo(!1,b)},p4=function(a){j4.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.l=new g.W({C:"div",G:"ytp-subscribe-card",J:[{C:"img",G:"ytp-author-image",L:{src:b.Md}},{C:"div",G:"ytp-subscribe-card-right",J:[{C:"div",G:"ytp-author-name",U:b.author},{C:"div",G:"html5-subscribe-button-container"}]}]});g.I(this,this.l);this.l.g(this.element);this.o=new g.gW("Subscribe",null,"Unsubscribe",null,!0,!1,b.Pf,b.subscribed,"trailer-endscreen",null,null,a);g.I(this,this.o);this.o.g(this.l.i["html5-subscribe-button-container"]);this.hide()},q4=function(a){var b=
g.X(a),c=g.fx||g.Dh?{style:"will-change: opacity"}:void 0,d=b.i,e=["ytp-videowall-still"];
b.g&&e.push("ytp-videowall-show-text");g.W.call(this,{C:"a",W:e,L:{href:"{{url}}",target:d?b.u:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},J:[{C:"div",G:"ytp-videowall-still-image",L:{style:"{{background}}"}},{C:"span",G:"ytp-videowall-still-info",J:[{C:"span",G:"ytp-videowall-still-info-bg",J:[{C:"span",G:"ytp-videowall-still-info-content",L:c,J:[{C:"span",G:"ytp-videowall-still-info-title",U:"{{title}}"},{C:"span",G:"ytp-videowall-still-info-author",
U:"{{author_and_views}}"},{C:"span",G:"ytp-videowall-still-info-live",U:"Live"},{C:"span",G:"ytp-videowall-still-info-duration",U:"{{duration}}"}]}]}]},{C:"span",W:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:[{C:"span",G:"ytp-videowall-still-listlabel-icon"},"Playlist",{C:"span",G:"ytp-videowall-still-listlabel-length",J:[" (",{C:"span",U:"{{playlist_length}}"},")"]}]},{C:"span",W:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],J:[{C:"span",G:"ytp-videowall-still-listlabel-mix-icon"},
"Mix",{C:"span",G:"ytp-videowall-still-listlabel-length",U:" (50+)"}]}]});this.A=d;this.l=a;this.o=null;this.u=new g.Ms(this);g.I(this,this.u);this.da("click",this.D);this.da("keypress",this.F);this.u.K(a,"videodatachange",this.B);g.X(a).F&&g.rO(a.app.O,this.element,this);this.B()},r4=function(a){g.JK(a.l,a.element);
var b=a.o.oa().videoId,c=a.o.getPlaylistId();g.mY(a.l.app,b,a.o.Zc,c,void 0,void 0,void 0)},s4=function(a){j4.call(this,a,"videowall-endscreen");
this.H=a;this.B=0;this.o=[];this.D=this.u=this.A=null;this.F=this.R=!1;this.O=null;this.aa=new g.Ms(this);g.I(this,this.aa);this.I=new g.N(g.Qa(g.L,this.element,"ytp-show-tiles"),0);g.I(this,this.I);var b=new g.W({C:"button",W:["ytp-button","ytp-endscreen-previous"],L:{"aria-label":"Previous"},J:[g.HP()]});g.I(this,b);b.g(this.element);b.da("click",this.rF,this);this.M=new g.ZC({C:"div",G:"ytp-endscreen-content"});g.I(this,this.M);this.M.g(this.element);b=new g.W({C:"button",W:["ytp-button","ytp-endscreen-next"],
L:{"aria-label":"Next"},J:[g.IP()]});g.I(this,b);b.g(this.element);b.da("click",this.qF,this);this.l=new k4(a);g.I(this,this.l);g.GK(this.player,this.l.element,4);this.hide()},t4=function(a){return g.HK(a.player)&&a.iu()&&!a.D},u4=function(a,b){return(0,g.G)(b.suggestions,function(c){c=g.kS(g.X(a.H),c);
g.I(a,c);return c})},v4=function(a){var b=a.Le();
b!=a.R&&(a.R=b,a.player.N("autonavvisibility"))},x4=function(a){g.UK.call(this,a);
this.g=null;this.i=new g.Ms(this);g.I(this,this.i);this.l=g.X(a);w4(a)?this.g=new s4(this.player):this.l.Ga?this.g=new p4(this.player):this.g=new j4(this.player);g.I(this,this.g);g.GK(this.player,this.g.element,4);this.Fz();this.i.K(a,"videodatachange",this.Fz,this);this.i.K(a,g.lE("endscreen"),this.HE,this);this.i.K(a,"crx_endscreen",this.IE,this)},w4=function(a){a=g.X(a);
return a.Ba&&!a.Ga};
g.t(j4,g.dD);j4.prototype.create=function(){this.created=!0};
j4.prototype.destroy=function(){this.created=!1};
j4.prototype.iu=function(){return!1};
j4.prototype.Le=function(){return!1};g.t(k4,g.W);g.h=k4.prototype;g.h.Il=function(){this.B&&(this.F.stop(),this.Ma(this.D),this.D=null,this.B.close(),this.B=null)};
g.h.jy=function(){g.cD(this,this.l.Le())};
g.h.yJ=function(){window.focus();this.Il()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.Fo=function(a){a=a||g.S(g.X(this.l).experiments,"autoplay_time")||1E4;var b=Math.min(g.P()-this.H,a);a=Math.min(b/a,1);this.I.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.l.getPresentingPlayerType()?o4(this,!0):this.o&&this.o.start()};
g.h.GJ=function(a){!g.$d(this.A.element,g.fs(a))&&g.nS(a,this.l)&&o4(this)};
g.h.RH=function(){g.oK(this.l,!0)};
g.h.VI=function(a){this.l.getPresentingPlayerType();this.show();l4(this,a)};
g.h.IA=function(a){this.l.getPresentingPlayerType();this.u&&this.u.oa().videoId==a.oa().videoId||(this.u=a,i4(this,a,"hqdefault.jpg"))};
g.h.WI=function(){this.l.getPresentingPlayerType();m4(this);this.hide()};
g.h.T=function(){m4(this);this.Il();g.W.prototype.T.call(this)};g.t(p4,j4);g.t(q4,g.W);q4.prototype.D=function(a){g.nS(a,this.l,this.A,this.o.Zc||void 0)&&r4(this)};
q4.prototype.F=function(a){switch(a.keyCode){case 13:case 32:g.ks(a)||(r4(this),g.js(a))}};
q4.prototype.B=function(){var a=this.l.getVideoData(),b=g.X(this.l);this.A=a.Rb?!1:b.i};g.t(s4,j4);g.h=s4.prototype;g.h.create=function(){j4.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.A=u4(this,a),this.u=a);this.Hf();this.aa.K(this.player,"appresize",this.Hf);this.aa.K(this.player,"onVideoAreaChange",this.Hf);this.aa.K(this.player,"videodatachange",this.sF);this.aa.K(this.player,"autonavchange",this.Pq);this.aa.K(this.player,"autonavcancel",this.pF);a=this.u.autonavState;a!=this.O&&this.Pq(a);this.aa.K(this.element,"transitionend",this.WK)};
g.h.destroy=function(){g.Os(this.aa);g.qf(this.o);this.o=[];this.A=null;j4.prototype.destroy.call(this);g.lo(this.element,"ytp-show-tiles");this.I.stop();this.O=this.u.autonavState};
g.h.iu=function(){return 1!=this.u.autonavState};
g.h.show=function(){j4.prototype.show.call(this);g.lo(this.element,"ytp-show-tiles");g.X(this.player).g?g.zo(this.I):this.I.start();(this.F||this.D&&this.D!=this.u.clientPlaybackNonce)&&g.oK(this.player,!1);t4(this)?(v4(this),2==this.u.autonavState?g.R(g.X(this.player).experiments,"fast_autonav_in_background")&&3==this.player.getVisibilityState()?o4(this.l,!0):l4(this.l):3==this.u.autonavState&&n4(this.l)):(g.oK(this.player,!0),v4(this))};
g.h.hide=function(){j4.prototype.hide.call(this);n4(this.l);v4(this)};
g.h.WK=function(a){g.fs(a)==this.element&&this.Hf()};
g.h.Hf=function(){if(this.A&&this.A.length){g.L(this.element,"ytp-endscreen-paginate");var a=g.xK(this.H,!0),b=g.sD(this.H);b&&(b=b.Ac()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.A.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,r=e/2,u=b<=f-2&&n>=r*m,z=e<=k-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&z)n-=p*m,e+=2;else if(u)n-=r*m,b+=2;else if(z)n-=p*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.od(a.width/m||1,1,1.21);n*=g.od(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.M.element;g.Th(a,m,n);g.Ah(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.l;f=this.A[0];c.u=f;i4(c,f,"hqdefault.jpg");g.M(this.element,"ytp-endscreen-takeover",t4(this));v4(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,r=0,d&&f>=b-2&&k>=e-
2?r=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(r=2):r=2),p=g.pd(p+this.B,l),0!=r){u=this.o[c];u||(u=new q4(this.player),this.o[c]=u,a.appendChild(u.element));z=Math.floor(n*k/e);var C=Math.floor(m*f/b),E=Math.floor(n*(k+r)/e)-z-4,F=Math.floor(m*(f+r)/b)-C-4;g.Ih(u.element,C,z);g.Th(u.element,F,E);g.Ah(u.element,"transitionDelay",(k+f)/20+"s");g.M(u.element,"ytp-videowall-still-mini",1==r);g.M(u.element,"ytp-videowall-still-large",2<r);r=u;p=this.A[p];r.o!=p&&(r.o=p,i4(r,p,g.jo(r.element,"ytp-videowall-still-large")?
"hqdefault.jpg":"mqdefault.jpg"),p=(p=p.Zc)&&p.itct)&&(u=r.l,g.X(u).F&&g.sO(u.app.O,r.element,p));c++}g.M(this.element,"ytp-endscreen-paginate",c<l);for(b=this.o.length-1;b>=c;b--)e=this.o[b],g.Wd(e.element),g.pf(e);this.o.length=c}};
g.h.sF=function(){var a=this.player.getVideoData();this.u!=a&&(this.B=0,this.A=u4(this,a),this.u=a,this.Hf())};
g.h.qF=function(){this.B+=this.o.length;this.Hf()};
g.h.rF=function(){this.B-=this.o.length;this.Hf()};
g.h.UD=function(){return!!this.l.o};
g.h.Pq=function(a){1==a?(this.F=!1,this.D=this.u.clientPlaybackNonce,m4(this.l),this.Fa()&&this.Hf()):(this.F=!0,this.Fa()&&t4(this)&&(2==a?l4(this.l):3==a&&n4(this.l)))};
g.h.pF=function(a){if(a){for(a=0;a<this.o.length;a++)g.KK(this.H,this.o[a].element,!0);this.Pq(1)}else this.D=null,this.F=!1;this.Hf()};
g.h.Le=function(){return this.Fa()&&t4(this)};g.t(x4,g.UK);g.h=x4.prototype;g.h.Gk=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!w4(this.player)||b;a=a.Lc;var c=g.NX(this.player.app);return b&&!a&&!c};
g.h.Le=function(){return this.g.Le()};
g.h.QD=function(){return this.Le()?this.g.UD():!1};
g.h.T=function(){g.CK(this.player,"endscreen");g.UK.prototype.T.call(this)};
g.h.load=function(){g.UK.prototype.load.call(this);this.g.show()};
g.h.unload=function(){g.UK.prototype.unload.call(this);this.g.hide();this.g.destroy()};
g.h.HE=function(a){this.Gk()&&(this.g.created||this.g.create(),"load"==a.getId()&&this.load())};
g.h.IE=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.Fz=function(){g.CK(this.player,"endscreen");var a=Math.max(1E3*(this.player.getVideoData().lengthSeconds-10),0);a=new g.iE(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.I(this,a);var b=new g.iE(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.I(this,b);g.zK(this.player,[a,b])};g.oV.endscreen=x4;})(_yt_player);
