(function(g){var window=this;var Opa=function(a,b){return g.Tb(a,b)},C5=function(){},Ppa=function(a){if(a.zc&&"function"==typeof a.zc)return a.zc();
if(g.v(a))return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Pb(a)},Qpa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||g.v(a))(0,g.B)(a,b,void 0);else{if(a.Gd&&"function"==typeof a.Gd)var c=a.Gd();else if(a.zc&&"function"==typeof a.zc)c=void 0;else if(g.La(a)||g.v(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Qb(a);d=Ppa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},D5=function(a){g.jn(a,"zx",g.ad());
return a},E5=function(a,b,c){g.Ka(c)||(c=[String(c)]);
g.on(a.l,b,c)},F5=function(a){return(a=g.Lo(a))?new ActiveXObject(a):new XMLHttpRequest},G5=function(a,b){return b+" ["+a.ba+" "+a.F+" "+a.getStatus()+"]"},Rpa=function(a){return"content-type"==a.toLowerCase()},H5=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.B&&(g.w.clearTimeout(a.B),a.B=null)},Spa=function(a){return g.Ld&&g.md(9)&&g.Ea(a.timeout)&&g.Ca(a.ontimeout)},I5=function(a){a.O||(a.O=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},J5=function(a,b){if(a.g){H5(a);
var c=a.g,d=a.P[0]?g.Ga:null;a.g=null;a.P=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},K5=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;I5(a);J5(a)},L5=function(a){return a.g?a.g.readyState:0},M5=function(a){if(a.i&&"undefined"!=typeof g.CY)if(a.P[1]&&4==L5(a)&&2==a.getStatus())G5(a,"Local request error detected and ignored");
else if(a.D&&4==L5(a))g.Ig(a.Sv,0,a);else if(a.dispatchEvent("readystatechange"),4==L5(a)){G5(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Sg(String(a.F))[1]||null;if(!f&&g.w.self&&g.w.self.location){var k=g.w.self.location.protocol;f=k.substr(0,k.length-1)}e=!Tpa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<L5(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";I5(a)}}finally{J5(a)}}},N5=function(a){g.Sf.call(this);
this.headers=new g.Ym;this.M=a||null;this.i=!1;this.P=this.g=null;this.ba=this.F="";this.u=0;this.l="";this.o=this.V=this.D=this.O=!1;this.A=0;this.B=null;this.Z="";this.I=this.R=!1},O5=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},Upa=function(a,b){var c=[];
g.Tk(b,function(d){try{var e=g.$o.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ca(e)?g.Zo(e)&&c.push(d):c.push(d)},a);
return c},Vpa=function(a,b){var c=Upa(a,b);
(0,g.B)(c,function(d){g.$o.prototype.remove.call(this,d)},a)},P5=function(a){if(a.bd){if(a.bd.locationOverrideToken)return{locationOverrideToken:a.bd.locationOverrideToken};
if(null!=a.bd.latitudeE7&&null!=a.bd.longitudeE7)return{latitudeE7:a.bd.latitudeE7,longitudeE7:a.bd.longitudeE7}}return null},Wpa=function(a,b){g.$a(a,b)||a.push(b)},Q5=function(a){var b=0,c;
for(c in a)b++;return b},R5=function(a,b){var c=b instanceof g.wc?b:g.Cc(b,/^data:image\//i.test(b));
a.src=g.xc(c)},Xpa=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))},Ypa=function(a){try{return g.w.JSON.parse(a)}catch(b){}a=String(a);
if(Xpa(a))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Zpa=function(a,b,c,d){var e=new g.an(null,void 0);
a&&g.bn(e,a);b&&g.cn(e,b);c&&g.dn(e,c);d&&(e.i=d);return e},S5=function(a){if(g.w.JSON)try{return g.w.JSON.parse(a)}catch(b){}return Ypa(a)},T5=function(){this.g=[];
this.i=[]},U5=function(a,b){g.eq[a]=!0;
var c=g.cq();c&&c.publish.apply(c,arguments);g.eq[a]=!1},V5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Ym;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",$pa(this,a.capabilities||""),aqa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},$pa=function(a,b){a.capabilities.clear();
(0,g.Xd)(b.split(","),g.Qa(Opa,bqa)).forEach(function(c){a.capabilities.add(c)})},aqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},W5=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},X5=function(a,b){return!!b&&(a.id==b||a.uuid==b)},Y5=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},cqa=function(a){return new W5(a)},Z5=function(a){return g.Ka(a)?(0,g.G)(a,cqa):[]},$5=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},a6=function(a){return g.Ka(a)?"["+(0,g.G)(a,$5).join(",")+"]":"null"},b6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},dqa=function(a){return(0,g.G)(a,function(b){return{key:b.id,
name:b.name}})},c6=function(a,b){return g.Xa(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},d6=function(a,b){return g.Xa(a,function(c){return X5(c,b)})},eqa=function(){var a=(0,g.vt)();
a&&Vpa(a,a.g.hf(!0))},e6=function(){var a=g.zt("yt-remote-connected-devices")||[];
g.pb(a);return a},fqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.G)(a,function(d,e){return 0==e?d:d.substring(c.length)})},f6=function(a){g.xt("yt-remote-connected-devices",a,86400)},h6=function(){if(g6)return g6;
var a=g.zt("yt-remote-device-id");a||(a=b6(),g.xt("yt-remote-device-id",a,31536E3));for(var b=e6(),c=1,d=a;g.$a(b,d);)c++,d=a+"#"+c;return g6=d},i6=function(){var a=e6(),b=h6();
g.$a(a,b);g.Bt()&&g.rb(a,b);a=fqa(a);if(0==a.length)try{g.Cs("remote_sid")}catch(c){}else try{g.ys("remote_sid",a.join(","),-1)}catch(c){}},j6=function(){return g.zt("yt-remote-session-browser-channel")},k6=function(){return g.zt("yt-remote-local-screens")||[]},l6=function(){g.xt("yt-remote-lounge-token-expiration",!0,86400)},gqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.G)(k6(),function(d){return d.loungeToken}),c=(0,g.G)(a,function(d){return d.loungeToken});
(0,g.ij)(c,function(d){return!g.$a(b,d)})&&l6();
g.xt("yt-remote-local-screens",a,31536E3)},hqa=function(a,b){g.xt("yt-remote-session-browser-channel",a);
g.xt("yt-remote-session-screen-id",b);var c=e6(),d=h6();g.$a(c,d)||c.push(d);f6(c);i6()},m6=function(a){a||(g.At("yt-remote-session-screen-id"),g.At("yt-remote-session-video-id"));
i6();a=e6();g.cb(a,h6());f6(a)},o6=function(){if(!n6){var a=g.jp();
a&&(n6=new g.Uo(a))}return n6?!!n6.get("yt-remote-use-staging-server"):!1},p6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},q6=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},s6=function(a){a.length?r6(a.shift(),function(){s6(a)}):t6()},iqa=function(a){return"chrome-extension://"+a+u6},r6=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},t6=function(){var a=q6();
a&&a(!1,"No cast extension found")},v6=function(){if(jqa){var a=2,b=q6(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;r6("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",t6,c)}},kqa=function(){v6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);s6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+u6,"//www.gstatic.com/eureka/clank"+u6])},w6=function(a,b,c){g.H.call(this);
this.A=null!=c?(0,g.y)(a,c):a;this.Vc=b;this.u=(0,g.y)(this.YC,this);this.g=!1;this.i=0;this.l=this.za=null;this.o=[]},x6=function(){},y6=function(a,b,c,d){this.g=a;
this.l=b;this.B=c;this.A=d||1;this.o=45E3;this.aa=new g.pn(this);this.i=new g.Hg;this.i.setInterval(250)},A6=function(a,b,c){a.Xh=1;
a.jg=D5(b.clone());a.rh=c;a.u=!0;z6(a,null)},B6=function(a,b,c,d,e){a.Xh=1;
a.jg=D5(b.clone());a.rh=null;a.u=c;e&&(a.Lz=!1);z6(a,d)},z6=function(a,b){a.Bi=(0,g.D)();
C6(a);a.Bg=a.jg.clone();E5(a.Bg,"t",a.A);a.Sk=0;a.tc=a.g.gp(a.g.Ik()?b:null);0<a.Lp&&(a.xn=new g.Jl((0,g.y)(a.TA,a,a.tc),a.Lp));a.aa.da(a.tc,"readystatechange",a.FL);var c=a.Wg?g.ac(a.Wg):{};a.rh?(a.fo="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.tc.send(a.Bg,a.fo,a.rh,c)):(a.fo="GET",a.Lz&&!g.Nd&&(c.Connection="close"),a.tc.send(a.Bg,a.fo,null,c));a.g.qe(1)},J6=function(a,b,c){for(var d=!0;!a.Mg&&a.Sk<c.length;){var e=lqa(a,c);
if(e==D6){4==b&&(a.kg=4,E6(15),d=!1);break}else if(e==F6){a.kg=4;E6(16);d=!1;break}else G6(a,e)}4==b&&0==c.length&&(a.kg=1,E6(17),d=!1);a.we=a.we&&d;d||(H6(a),I6(a))},lqa=function(a,b){var c=a.Sk,d=b.indexOf("\n",c);
if(-1==d)return D6;c=Number(b.substring(c,d));if(isNaN(c))return F6;d+=1;if(d+c>b.length)return D6;var e=b.substr(d,c);a.Sk=d+c;return e},M6=function(a,b){a.Bi=(0,g.D)();
C6(a);var c=b?window.location.hostname:"";a.Bg=a.jg.clone();g.jn(a.Bg,"DOMAIN",c);g.jn(a.Bg,"t",a.A);try{a.ze=new ActiveXObject("htmlfile")}catch(n){H6(a);a.kg=7;E6(22);I6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in K6)k=K6[l];else if(l in L6)k=K6[l]=L6[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
K6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Qc(g.pc("b/12014412"),d+"</body></html>");a.ze.open();a.ze.write(g.Lc(c));a.ze.close();a.ze.parentWindow.m=(0,g.y)(a.ZK,a);a.ze.parentWindow.d=(0,g.y)(a.Ry,a,!0);a.ze.parentWindow.rpcClose=(0,g.y)(a.Ry,a,!1);c=a.ze.createElement("DIV");a.ze.parentWindow.document.body.appendChild(c);d=g.Bc(a.Bg.toString());d=g.Xc(g.yc(d));d=g.Qc(g.pc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Rc(c,d);a.g.qe(1)},C6=function(a){a.Rs=(0,g.D)()+a.o;
N6(a,a.o)},N6=function(a,b){if(null!=a.Si)throw Error("WatchDog timer not null");
a.Si=O6((0,g.y)(a.jL,a),b)},P6=function(a){a.Si&&(g.w.clearTimeout(a.Si),a.Si=null)},I6=function(a){a.g.Qv()||a.Mg||a.g.gn(a)},H6=function(a){P6(a);
g.pf(a.xn);a.xn=null;a.i.stop();g.rn(a.aa);if(a.tc){var b=a.tc;a.tc=null;b.abort();b.dispose()}a.ze&&(a.ze=null)},G6=function(a,b){try{a.g.Ly(a,b),a.g.qe(4)}catch(c){}},R6=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;Q6(a,b,function(k){k?c(!0):g.w.setTimeout(function(){R6(a,b,c,d,f)},f)})}},Q6=function(a,b,c){var d=new Image;
d.onload=function(){try{S6(d),c(!0)}catch(e){}};
d.onerror=function(){try{S6(d),c(!1)}catch(e){}};
d.onabort=function(){try{S6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{S6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
R5(d,a)},S6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},T6=function(a){this.g=a;
this.i=new x6},V6=function(a){var b=U6(a.g,a.bj,"/mail/images/cleardot.gif");
D5(b);R6(b.toString(),5E3,(0,g.y)(a.jC,a),3,2E3);a.qe(1)},X6=function(a){var b=a.g.F;
if(null!=b)E6(5),b?(E6(11),W6(a.g,a,!1)):(E6(12),W6(a.g,a,!0));else if(a.Cd=new y6(a,void 0,void 0,void 0),a.Cd.Wg=a.Jp,b=a.g,b=U6(b,b.Ik()?a.Gj:null,a.Kp),E6(5),!g.Ld||g.nd(10))E5(b,"TYPE","xmlhttp"),B6(a.Cd,b,!1,a.Gj,!1);else{E5(b,"TYPE","html");var c=a.Cd;a=!!a.Gj;c.Xh=3;c.jg=D5(b.clone());M6(c,a)}},Y6=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new x6;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},mqa=function(a,b){this.g=a;
this.map=b;this.context=null},Z6=function(a){g.rf.call(this,"statevent",a)},$6=function(a,b){g.rf.call(this,"timingevent",a);
this.size=b},a7=function(a){g.rf.call(this,"serverreachability",a)},e7=function(a){b7(a);
if(3==a.g){var b=a.pk++,c=a.Tl.clone();g.jn(c,"SID",a.l);g.jn(c,"RID",b);g.jn(c,"TYPE","terminate");c7(a,c);b=new y6(a,a.l,b,void 0);b.Xh=2;b.jg=D5(c.clone());R5(new Image,b.jg.toString());b.Bi=(0,g.D)();C6(b)}d7(a)},g7=function(a){a.AC(1,0);
a.Tl=U6(a,null,a.Ip);f7(a)},b7=function(a){a.Zf&&(a.Zf.abort(),a.Zf=null);
a.Qb&&(a.Qb.cancel(),a.Qb=null);a.kf&&(g.w.clearTimeout(a.kf),a.kf=null);h7(a);a.yd&&(a.yd.cancel(),a.yd=null);a.fg&&(g.w.clearTimeout(a.fg),a.fg=null)},i7=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new mqa(a.kH++,b));2!=a.g&&3!=a.g||f7(a)},f7=function(a){a.yd||a.fg||(a.fg=O6((0,g.y)(a.Qy,a),0),a.Rh=0)},l7=function(a,b){if(1==a.g){if(!b){a.pk=Math.floor(1E5*Math.random());
var c=a.pk++,d=new y6(a,"",c,void 0);d.Wg=null;var e=j7(a),f=a.Tl.clone();g.jn(f,"RID",c);g.jn(f,"CVER","1");c7(a,f);A6(d,f,e);a.yd=d;a.g=2}}else 3==a.g&&(b?k7(a,b):0==a.i.length||a.yd||k7(a))},k7=function(a,b){if(b)if(6<a.Ng){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.pk-1;var d=j7(a)}else c=b.B,d=b.rh;else c=a.pk++,d=j7(a);var e=a.Tl.clone();g.jn(e,"SID",a.l);g.jn(e,"RID",c);g.jn(e,"AID",a.hi);c7(a,e);c=new y6(a,a.l,c,a.Rh+1);c.Wg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.yd=c;A6(c,e,d)},c7=function(a,b){if(a.Tc){var c=a.Tc.uv();
c&&g.Jb(c,function(d,e){g.jn(b,e,d)})}},j7=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Ng&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Ng?e:f-d;try{g.Jb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},m7=function(a){a.Qb||a.kf||(a.B=1,a.kf=O6((0,g.y)(a.Py,a),0),a.Lh=0)},o7=function(a){if(a.Qb||a.kf||3<=a.Lh)return!1;
a.B++;a.kf=O6((0,g.y)(a.Py,a),n7(a,a.Lh));a.Lh++;return!0},W6=function(a,b,c){a.co=c;
a.He=b.xf;a.A||g7(a)},h7=function(a){null!=a.Rg&&(g.w.clearTimeout(a.Rg),a.Rg=null)},n7=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},q7=function(a,b){if(2==b||9==b){var c=null;
a.Tc&&(c=null);var d=(0,g.y)(a.jM,a);c||(c=new g.an("//www.google.com/images/cleardot.gif"),D5(c));Q6(c.toString(),1E4,d)}else E6(2);p7(a,b)},p7=function(a,b){a.g=0;
a.Tc&&a.Tc.tu(b);d7(a);b7(a)},d7=function(a){a.g=0;
a.He=-1;if(a.Tc)if(0==a.o.length&&0==a.i.length)a.Tc.Uo();else{g.fb(a.o);var b=g.fb(a.i);a.o.length=0;a.i.length=0;a.Tc.Uo(b)}},U6=function(a,b,c){var d=g.kn(c);
if(""!=d.g)b&&g.cn(d,b+"."+d.g),g.dn(d,d.u);else{var e=window.location;d=Zpa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.oj&&g.Jb(a.oj,function(f,k){g.jn(d,k,f)});
g.jn(d,"VER",a.Ng);c7(a,d);return d},O6=function(a,b){if(!g.Ma(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},E6=function(a){r7.dispatchEvent(new Z6(r7,a))},s7=function(){},nqa=function(a,b){this.action=a;
this.params=b||{}},t7=function(a,b){g.H.call(this);
this.g=new g.N(this.RK,0,this);g.I(this,this.g);this.Vc=5E3;this.i=0;if(g.Ma(a))b&&(a=(0,g.y)(a,b));else if(a&&g.Ma(a.handleEvent))a=(0,g.y)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},u7=function(a,b,c){this.H=a;
this.A=b;this.l=new g.To;this.i=new t7(this.OL,this);this.g=null;this.Za=!1;this.u=null;this.F="";this.D=this.o=0;this.B=[];this.I=c||!1},oqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.co,sessionId:a.g.l,arrayId:a.g.hi}},v7=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&l7(a.g),e7(a.g));a.D=0},w7=function(a){return!!a.g&&3==a.g.g},pqa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},x7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=g.Vg(a)||"";b&&(this.port=":"+b);this.domain=g.Ug(a)||"";a=g.Hb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Gb(a,"10.0")&&(this.i=!1))},y7=function(a,b){var c=a.g;
if(g.Ca(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.dh(c+b,{})},z7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.o,d,!0),onError:g.Qa(a.l,e),pd:g.Qa(a.u,e)};c&&(a.rb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Xq(b,a)},qqa=function(){var a=A7;
B7();C7.push(a);D7(C7)},E7=function(a,b){B7();
var c=C7,d=rqa(a,String(b));0==c.length?sqa(d):(D7(c),(0,g.B)(c,function(e){e(d)}))},B7=function(){C7||(C7=g.x("yt.mdx.remote.debug.handlers_")||[],g.Fa("yt.mdx.remote.debug.handlers_",C7,void 0))},sqa=function(a){var b=(F7+1)%50;
F7=b;G7[b]=a;H7||(H7=49==b)},D7=function(a){var b=G7;
if(b[0]){var c=F7,d=H7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(f){f(e)})}while(d!=c);
G7=Array(50);F7=-1;H7=!1}},rqa=function(a,b){var c=((0,g.D)()-tqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},I7=function(a){g.Q.call(this);
this.B=a;this.g=[]},J7=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},uqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Xd)(a.g,function(f){return!!c6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=J7(a,b[d])||c;return c},vqa=function(a,b){var c=a.g.length;
a.g=(0,g.Xd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},K7=function(a,b,c,d){g.Q.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.za=NaN},M7=function(a){I7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;L7(this);this.info("Initializing with "+a6(this.g))},wqa=function(a){if(a.g.length){var b=(0,g.G)(a.g,function(d){return d.id}),c=y7(a.l,"/pairing/get_lounge_token_batch");
z7(a.l,c,{screen_ids:b.join(",")},(0,g.y)(a.iD,a),(0,g.y)(a.hD,a))}},L7=function(a){var b=Z5(k6());
b=(0,g.Xd)(b,function(c){return!c.uuid});
return uqa(a,b)},N7=function(a,b){gqa((0,g.G)(a.g,Y5));
b&&l6()},P7=function(a,b){g.Q.call(this);
this.A=b;var c=g.zt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.$a(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;O7("Initialized with "+g.Mg(this.g))},xqa=function(a,b,c){var d=y7(a.u,"/pairing/get_screen_availability");
z7(a.u,d,{lounge_token:b.token},(0,g.y)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.y)(function(){c(!1)},a))},Q7=function(a,b){a:if(Q5(b)!=Q5(a.g))var c=!1;
else{c=g.Qb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(O7("Updated online screens: "+g.Mg(a.g)),a.g=b,a.N("screenChange"));yqa(a)},R7=function(a){isNaN(a.l)||g.bq(a.l);
a.l=g.$p((0,g.y)(a.Sr,a),0<a.o&&a.o<(0,g.D)()?2E4:1E4)},O7=function(a){E7("OnlineScreenService",a)},zqa=function(a){var b={};
(0,g.B)(a.A(),function(c){c.token?b[c.token]=c.id:this.Jb("Requesting availability of screen w/o lounge token.")});
return b},yqa=function(a){a=g.Qb(g.Kb(a.g,function(b){return b}));
g.pb(a);a.length?g.xt("yt-remote-online-screen-ids",a.join(","),60):g.At("yt-remote-online-screen-ids")},S7=function(a){I7.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};Aqa(this)},Cqa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Id();if(k=(c?d6(k,c):null)||d6(k,b)){k.uuid=b;var l=T7(a,k);xqa(a.i,l,function(m){e(m?l:null)})}else c?Bqa(a,c,(0,g.y)(function(m){var n=T7(this,new W5({name:d,
screenId:c,loungeToken:m,dialId:b||""}));xqa(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},Dqa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Bqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={rb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Xq(y7(a.A,"/pairing/get_lounge_token_batch"),e)},Eqa=function(a){a.g=a.l.Id();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+a6(a.g))},Aqa=function(a){U7(a);
a.l=new M7(a.A);a.l.subscribe("screenChange",(0,g.y)(a.rD,a));Eqa(a);a.o=Z5(g.zt("yt-remote-automatic-screen-cache")||[]);U7(a);a.info("Initializing automatic screens: "+a6(a.o));a.i=new P7(a.A,(0,g.y)(a.Id,a,!0));a.i.subscribe("screenChange",(0,g.y)(function(){this.N("onlineScreenChange")},a))},T7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=d6(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.xt("yt-remote-automatic-screen-cache",(0,g.G)(a.o,Y5)));U7(a);a.u[b.uuid]=b.id;g.xt("yt-remote-device-id-map",a.u,31536E3);return b},U7=function(a){a.u=g.zt("yt-remote-device-id-map")||{}},V7=function(a,b,c){g.Q.call(this);
this.P=c;this.F=a;this.i=b;this.l=null},W7=function(a,b){E7(a.P,b)},X7=function(a,b){V7.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.y)(this.JM,this);this.u=(0,g.y)(this.vL,this);this.o=g.$p((0,g.y)(function(){Fqa(this,null)},this),12E4)},Gqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Mg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ga,(0,g.y)(function(){W7(this,"Failed to send message: getMdxSessionStatus.")},a)):W7(a,"Sending yt message without session: "+g.Mg(b))},Fqa=function(a,b){g.bq(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.y)(a.hn,a),d=(0,g.y)(a.Ld,a);a.Jv(b,c,d,5)}}else a.Ld(Error("Waiting for session status timed out."))},Y7=function(a,b,c){V7.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.M=c;this.u=null;this.B=g.Ga;this.A=NaN;this.I=(0,g.y)(this.MM,this);this.g=g.Ga},Hqa=function(a){a.g=a.F.YA(a.H,a.i.label,a.i.friendlyName,(0,g.y)(function(b){this.g=g.Ga;
this.hn(b)},a),(0,g.y)(function(b){this.g=g.Ga;
this.Ld(b)},a))},Iqa=function(a){var b={};
b.pairingCode=a.H;b.theme=a.M;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}o6()&&(b.env_useStageMdx=1);return g.bh(b)},Z7=function(a,b){V7.call(this,a,b,"ManualSession");
this.g=g.$p((0,g.y)(this.ji,this,null),150)},$7=function(a,b,c,d){g.Q.call(this);
this.i=a;this.B=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.y)(this.aK,this)},Jqa=function(a,b){return b?g.Xa(a.l,function(c){return X5(b,c.label)},a):null},a8=function(a){E7("Controller",a)},A7=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},b8=function(a){return a.u||!!a.l.length||!!a.g},c8=function(a,b,c){b!=a.g&&(g.pf(a.g),(a.g=b)?(c?a.N("yt-remote-cast2-receiver-resumed",b.i):a.N("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.y)(a.Oy,a,b)),b.l?a.N("yt-remote-cast2-session-change",b.l):c&&a.g.ji(null)):a.N("yt-remote-cast2-session-change",null))},Kqa=function(a){var b=a.i.XA(),c=a.g&&a.g.i;
a=(0,g.G)(b,function(d){c&&X5(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=Jqa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Qqa=function(a,b,c,d,e,f,k){Lqa()?Mqa(b,e,f,k)&&(e8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?Nqa(a,c):(window.__onGCastApiAvailable=function(l,m){l?Nqa(a,c):(f8("Failed to load cast API: "+m),g8(!1),e8(!1),g.At("yt-remote-cast-available"),g.At("yt-remote-cast-receiver"),Oqa(),c(!1))},d?g.mq("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?kqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?t6():(v6(),s6(Pqa.map(iqa))))):d8("Cannot initialize because not running Chrome")},Oqa=function(){d8("dispose");
var a=h8();a&&a.dispose();g.Fa("yt.mdx.remote.cloudview.instance_",null,void 0);Rqa(!1);g.hq(i8);i8.length=0},j8=function(){return!!g.zt("yt-remote-cast-installed")},Sqa=function(){var a=g.zt("yt-remote-cast-receiver");
return a?a.friendlyName:null},Tqa=function(){d8("clearCurrentReceiver");
g.At("yt-remote-cast-receiver")},Uqa=function(){return j8()?h8()?h8().getCastSession():(f8("getCastSelector: Cast is not initialized."),null):(f8("getCastSelector: Cast API is not installed!"),null)},l8=function(){j8()?h8()?k8()?(d8("Requesting cast selector."),h8().requestSession()):(d8("Wait for cast API to be ready to request the session."),i8.push(g.gq("yt-remote-cast2-api-ready",l8))):f8("requestCastSelector: Cast is not initialized."):f8("requestCastSelector: Cast API is not installed!")},m8=
function(a,b){k8()?h8().setConnectedScreenStatus(a,b):f8("setConnectedScreenStatus called before ready.")},Lqa=function(){var a=0<=g.Hb.search(/ (CrMo|Chrome|CriOS)\//);
return g.fx||a},Vqa=function(a,b){h8().init(a,b)},Mqa=function(a,b,c,d){var e=!1;
h8()||(a=new $7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.xt("yt-remote-cast-available",f);U5("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){d8("onReceiverSelected: "+f.friendlyName);
g.xt("yt-remote-cast-receiver",f);U5("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){d8("onReceiverResumed: "+f.friendlyName);
g.xt("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){d8("onSessionChange: "+$5(f));
f||g.At("yt-remote-cast-receiver");U5("yt-remote-cast2-session-change",f)}),g.Fa("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
d8("cloudview.createSingleton_: "+e);return e},h8=function(){return g.x("yt.mdx.remote.cloudview.instance_")},Nqa=function(a,b){g8(!0);
e8(!1);Vqa(a,function(c){c?(Rqa(!0),g.jq("yt-remote-cast2-api-ready")):(f8("Failed to initialize cast API."),g8(!1),g.At("yt-remote-cast-available"),g.At("yt-remote-cast-receiver"),Oqa());b(c)})},d8=function(a){E7("cloudview",a)},f8=function(a){E7("cloudview",a)},g8=function(a){d8("setCastInstalled_ "+a);
g.xt("yt-remote-cast-installed",a)},k8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},Rqa=function(a){d8("setApiReady_ "+a);
g.Fa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},e8=function(a){g.Fa("yt.mdx.remote.cloudview.initializing_",a,void 0)},n8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.B=0;this.g=null;this.hasNext=this.Je=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},o8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Je=!1;a.hasNext=!1;a.B=0;a.A=(0,g.D)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},p8=function(a){return 1==a.playerState?((0,g.D)()-a.A)/1E3:0},q8=function(a,b){a.B=b;
a.A=(0,g.D)()},r8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.D)()-a.A)/1E3+a.B;
case -1E3:return 0}return a.B},s8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&o8(a)},t8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.bc(a.g);b.hasPrevious=a.Je;b.hasNext=a.hasNext;b.playerTime=a.B;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},v8=function(a,b){g.Q.call(this);
this.g=0;this.o=a;this.A=[];this.u=new T5;this.l=this.i=null;this.F=(0,g.y)(this.UH,this);this.B=(0,g.y)(this.rk,this);this.D=(0,g.y)(this.TH,this);this.H=(0,g.y)(this.gI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Us,this),Wqa(this))):c=3;0!=c&&(b?this.Us(c):g.$p((0,g.y)(function(){this.Us(c)},this),0));
var d=Uqa();d&&u8(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},w8=function(a){return new n8(a.o.getPlayerContextData())},Wqa=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Qa(this.XJ,b),this))},a)},Xqa=function(a){(0,g.B)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},x8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},z8=function(a,b,c){var d=w8(a);
q8(d,c);-1E3!=d.playerState&&(d.playerState=b);y8(a,d)},A8=function(a,b,c){a.o.sendMessage(b,c)},y8=function(a,b){Xqa(a);
a.o.setPlayerContextData(t8(b));Wqa(a)},u8=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.B),a.rk(null));
a.l=b;a.l&&(E7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.B),a.l.media.length&&a.rk(a.l.media[0]))},Yqa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=w8(a);b.contentId!=d.videoId&&E7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;q8(d,a.i.getEstimatedTime());y8(a,d)}else E7("CP","No cast media video. Ignoring state update.")},B8=function(a,b,c){return(0,g.y)(function(d){this.Jb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Jb("Retrying "+b+" using MDx browser channel."),A8(this,b,c))},a)},C8=function(a,b,c){g.Q.call(this);
this.u=NaN;this.M=!1;this.H=this.F=this.I=this.P=NaN;this.O=[];this.o=this.B=this.l=this.Qa=this.g=null;this.na=a;this.O.push(g.ds(window,"beforeunload",(0,g.y)(this.bD,this)));this.i=[];this.Qa=new n8;this.V=b.id;this.g=Zqa(this,c);this.g.subscribe("handlerOpened",this.YH,this);this.g.subscribe("handlerClosed",this.VH,this);this.g.subscribe("handlerError",this.WH,this);this.g.subscribe("handlerMessage",this.XH,this);pqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Qa.videoId;
g.Bt()&&g.xt("yt-remote-session-video-id",d)},this)},D8=function(a){E7("conn",a)},Zqa=function(a,b){return new u7(y7(a.na,"/bc"),b)},E8=function(a,b){a.N("proxyStateChange",b)},$qa=function(a){a.u=g.$p((0,g.y)(function(){D8("Connecting timeout");
this.A(1)},a),2E4)},F8=function(a){g.bq(a.u);
a.u=NaN},G8=function(a){g.bq(a.P);
a.P=NaN},ara=function(a){H8(a);
a.I=g.$p((0,g.y)(function(){I8(this,"getNowPlaying")},a),2E4)},H8=function(a){g.bq(a.I);
a.I=NaN},cra=function(a,b){b&&(F8(a),G8(a));
b==(w7(a.g)&&isNaN(a.u))?b&&(E8(a,1),I8(a,"getSubtitlesTrack")):b?(a.R()&&a.Qa.reset(),E8(a,1),I8(a,"getNowPlaying"),bra(a)):a.A(1)},dra=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Qa.videoId&&(g.Wb(b.params)?a.Qa.g=null:a.Qa.g=b.params,a.N("remotePlayerChange"))},era=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Qa.listId=b.params.listId||a.Qa.listId;s8(a.Qa,c,d);a.N("remoteQueueChange")},gra=function(a,b){b.params=b.params||{};
era(a,b);fra(a,b);a.N("autoplayDismissed")},fra=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
q8(a.Qa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Qa.playerState&&(c=-1E3);a.Qa.playerState=c;c=Number(b.params.loadedTime);a.Qa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Qa.D=isNaN(c)?0:c;c=a.Qa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Qa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Qa.playerState?ara(a):H8(a);a.N("remotePlayerChange")},hra=function(a,b){if(-1E3!=
a.Qa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Qa.playerState=c;c=parseInt(b.params.currentTime,10);q8(a.Qa,isNaN(c)?0:c);a.N("remotePlayerChange")}},ira=function(a,b){var c="true"==b.params.muted;
a.Qa.volume=parseInt(b.params.volume,10);a.Qa.muted=c;a.N("remotePlayerChange")},jra=function(a,b){a.B=b.params.videoId;
a.N("nowAutoplaying",parseInt(b.params.timeout,10))},kra=function(a,b){var c="true"==b.params.hasNext;
a.Qa.Je="true"==b.params.hasPrevious;a.Qa.hasNext=c;a.N("previousNextChange")},bra=function(a){g.bq(a.H);
a.H=g.$p((0,g.y)(a.A,a,1),864E5)},I8=function(a,b,c){c?D8("Sending: action="+b+", params="+g.Mg(c)):D8("Sending: action="+b);
a.g.sendMessage(b,c)},J8=function(a){I7.call(this,"ScreenServiceProxy");
this.Hc=a;this.i=[];this.i.push(this.Hc.$_s("screenChange",(0,g.y)(this.HM,this)));this.i.push(this.Hc.$_s("onlineScreenChange",(0,g.y)(this.BJ,this)))},pra=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Sp("MDX_CONFIG")||b;eqa();i6();K8||(K8=new x7(b?b.loungeApiHost:void 0),o6()&&(K8.g="/api/loungedev"));L8||(L8=g.x("yt.mdx.remote.deferredProxies_")||[],g.Fa("yt.mdx.remote.deferredProxies_",L8,void 0));lra();var c=M8();if(!c){var d=new S7(K8);g.Fa("yt.mdx.remote.screenService_",d,void 0);c=M8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Qqa(a,d,function(m){m?N8()&&m8(N8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){U5("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.Fa("yt.mdx.remote.initialized_",!0,void 0),O8("Initializing: "+g.Mg(b)),P8.push(g.gq("yt-remote-cast2-availability-change",function(){U5("yt-remote-receiver-availability-change")})),P8.push(g.gq("yt-remote-cast2-receiver-selected",function(){Q8(null);
U5("yt-remote-auto-connect","cast-selector-receiver")})),P8.push(g.gq("yt-remote-cast2-receiver-resumed",function(){U5("yt-remote-receiver-resumed","cast-selector-receiver")})),P8.push(g.gq("yt-remote-cast2-session-change",mra)),P8.push(g.gq("yt-remote-connection-change",function(m){m?m8(N8(),"YouTube TV"):R8()||(m8(null,null),Tqa())})),a=S8(),b.isAuto&&(a.id+="#dial"),g.Oq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),O8(" -- with channel params: "+
g.Mg(a)),nra(a),c.start(),N8()||ora())},rra=function(){var a=qra();
j8()&&g.zt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},qra=function(){var a=M8().Hc.$_gos();
var b=T8();b&&U8()&&(c6(a,b)||a.push(b));return dqa(a)},V8=function(){var a=sra();
!a&&j8()&&Sqa()&&(a={key:"cast-selector-receiver",name:Sqa()});return a},sra=function(){var a=qra(),b=T8();
b||(b=R8());return g.Xa(a,function(c){return b&&X5(b,c.key)?!0:!1})},T8=function(){var a=N8();
if(!a)return null;var b=M8().Id();return d6(b,a)},mra=function(a){O8("remote.onCastSessionChange_: "+$5(a));
if(a){var b=T8();b&&b.id==a.id?m8(b.id,"YouTube TV"):(b&&W8(),X8(a,1))}else U8()&&W8()},W8=function(){k8()?h8().stopSession():f8("stopSession called before API ready.");
var a=U8();a&&(a.disconnect(1),Y8(null))},Z8=function(){var a=U8();
return!!a&&3!=a.getProxyState()},O8=function(a){E7("remote",a)},M8=function(){if(!$8){var a=g.x("yt.mdx.remote.screenService_");
$8=a?new J8(a):null}return $8},N8=function(){return g.x("yt.mdx.remote.currentScreenId_")},tra=function(a){g.Fa("yt.mdx.remote.currentScreenId_",a,void 0)},ura=function(){return g.x("yt.mdx.remote.connectData_")},Q8=function(a){g.Fa("yt.mdx.remote.connectData_",a,void 0)},U8=function(){return g.x("yt.mdx.remote.connection_")},Y8=function(a){var b=U8();
Q8(null);a||tra("");g.Fa("yt.mdx.remote.connection_",a,void 0);L8&&((0,g.B)(L8,function(c){c(a)}),L8.length=0);
b&&!a?U5("yt-remote-connection-change",!1):!b&&a&&U5("yt-remote-connection-change",!0)},R8=function(){var a=g.Bt();
if(!a)return null;var b=M8().Id();return d6(b,a)},X8=function(a,b){T8()&&T8();
tra(a.id);var c=new C8(K8,a,S8());c.connect(b,ura());c.subscribe("beforeDisconnect",function(d){U5("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){U8()&&Y8(null)});
Y8(c)},ora=function(){var a=R8();
a?(O8("Resume connection to: "+$5(a)),X8(a,0)):(m6(),Tqa(),O8("Skipping connecting because no session screen found."))},lra=function(){var a=S8();
if(g.Wb(a)){a=h6();var b=g.zt("yt-remote-session-name")||"",c=g.zt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Fa("yt.mdx.remote.channelParams_",a,void 0)}},S8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},nra=function(a){a?(g.xt("yt-remote-session-app",a.app),g.xt("yt-remote-session-name",a.name)):(g.At("yt-remote-session-app"),g.At("yt-remote-session-name"));
g.Fa("yt.mdx.remote.channelParams_",a,void 0)},a9=function(a,b,c){g.H.call(this);
this.u=a;this.i=b;this.l=new g.Ms(this);g.I(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.TI);this.l.K(b,"captionschanged",this.SH);this.l.K(b,"captionssettingschanged",this.lA);this.l.K(b,"videoplayerreset",this.jn);this.l.K(b,"mdxautoplaycancel",this.iC);this.O=this.l.K(b,"onVolumeChange",this.zy);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.Ky,this);c.subscribe("remotePlayerChange",this.uk,this);c.subscribe("remoteQueueChange",this.jn,this);c.subscribe("autoplayUpNext",this.ly,
this);c.subscribe("previousNextChange",this.Hy,this);c.subscribe("nowAutoplaying",this.Dy,this);c.subscribe("autoplayDismissed",this.ky,this);this.suggestion=null;this.F=new g.zC(64);this.o=new g.N(this.jA,500,this);g.I(this,this.o);this.A=new g.N(this.kA,1E3,this);g.I(this,this.A);this.I=new w6(this.rM,0,this);g.I(this,this.I);this.B={};this.P=new g.N(this.KA,1E3,this);g.I(this,this.P);this.H=new g.Jl(this.yF,1E3,this);g.I(this,this.H);this.M=g.Ga;this.lA();this.jn();this.uk()},b9=function(a,b){a.u.qd(b,
a.i.getVideoData().lengthSeconds)},vra=function(a){b9(a,0);
a.o.stop();c9(a,new g.zC(64))},e9=function(a,b){if(d9(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.dc(c,b));a.g.Zz(a.i.getVideoData(1).videoId,c);a.B=w8(a.g).g}},f9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Sa;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.zf,P5(c));c9(a,new g.zC(1))},wra=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{dQ:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},d9=function(a){return w8(a.g).videoId==a.i.getVideoData(1).videoId},c9=function(a,b){a.A.stop();
var c=a.F;if(!g.FC(c,b)){var d=g.U(b,2);d!=g.U(a.F,2)&&g.uK(a.i,d);a.F=b;xra(a.u,c,b)}},g9=function(a){g.W.call(this,{C:"div",
G:"ytp-remote",J:[{C:"div",G:"ytp-remote-display-status",J:[{C:"div",G:"ytp-remote-display-status-icon",J:[g.FP()]},{C:"div",G:"ytp-remote-display-status-text",U:"{{statustext}}"}]}]});this.l=new g.pQ(this,250);g.I(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);yra(this,g.qK(a))},yra=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.EN("Error on $RECEIVER_NAME",c):g.GC(b)||g.U(b,4)?g.EN("Playing on $RECEIVER_NAME",c):g.EN("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},h9=function(a,b){g.ZT.call(this,"Play on",0,a,b);
this.l=a;this.F={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},i9=function(a){g.UK.call(this,a);
this.i={key:b6(),name:"This computer"};this.o=null;this.u=[];this.B=this.g=null;this.A=[this.i];this.l=this.i;this.ck=new g.zC(64);this.D=0;this.ym=-1;if(!g.kz(g.X(this.player))){a=this.player;var b=g.sD(a);b&&(b=b.Sm())&&(b=new h9(a,b),g.I(this,b));b=new g9(a);g.I(this,b);g.GK(a,b.element,4)}},xra=function(a,b,c){a.ck=c;
a.player.N("presentingplayerstatechange",new g.GD(c,b))},j9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)W8();
else{a.l=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.oa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.zf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(d=P5(d))&&(c.locationInfo=d);d=c}else d=null;O8("Connecting to: "+g.Mg(b));"cast-selector-receiver"==b.key?
(Q8(d||null),k8()?h8().setLaunchParams(d||null):f8("setLaunchParams called before ready.")):!d&&Z8()&&N8()==b.key?U5("yt-remote-connection-change",!0):(W8(),Q8(d||null),d=M8().Id(),(d=d6(d,b.key))&&X8(d,1))}},Tpa=/^https?$/i,zra=["POST",
"PUT"];g.A(N5,g.Sf);g.h=N5.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.F+"; newUri="+a);b=b?b.toUpperCase():"GET";this.F=a;this.l="";this.u=0;this.ba=b;this.O=!1;this.i=!0;this.g=this.M?F5(this.M):F5(g.ZY);this.P=this.M?this.M.getOptions():g.ZY.getOptions();this.g.onreadystatechange=(0,g.y)(this.Sv,this);try{C5(G5(this,"Opening Xhr")),this.V=!0,this.g.open(b,String(a),!0),this.V=!1}catch(f){C5(G5(this,"Error opening Xhr: "+f.message));K5(this,f);return}a=c||
"";var e=this.headers.clone();d&&Qpa(d,function(f,k){e.set(k,f)});
d=g.Xa(e.Gd(),Rpa);c=g.w.FormData&&a instanceof g.w.FormData;!g.$a(zra,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.Z&&(this.g.responseType=this.Z);"withCredentials"in this.g&&this.g.withCredentials!==this.R&&(this.g.withCredentials=this.R);try{H5(this),0<this.A&&(this.I=Spa(this.g),C5(G5(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.y)(this.Tv,this)):this.B=g.Ig(this.Tv,this.A,this)),C5(G5(this,"Sending request")),this.D=!0,this.g.send(a),this.D=!1}catch(f){C5(G5(this,"Send error: "+f.message)),K5(this,f)}};
g.h.Tv=function(){"undefined"!=typeof g.CY&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,G5(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(G5(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),J5(this))};
g.h.T=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),J5(this,!0));N5.Ha.T.call(this)};
g.h.Sv=function(){this.ea()||(this.V||this.D||this.o?M5(this):this.ZJ())};
g.h.ZJ=function(){M5(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<L5(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.v(this.l)?this.l:String(this.l)};
var L6={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},K6={"'":"\\'"},Ara={};g.h=T5.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.$a(this.g,a)||g.$a(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Dma)(b,a);0<=c?(g.bb(b,c),b=!0):b=!1;return b||g.cb(this.i,a)};
g.h.zc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var bqa={gN:"atp",rP:"ska",gP:"que",FO:"mus",qP:"sus",WN:"dsp",nP:"seq"};V5.prototype.ag=function(){var a=new V5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var n6,g6="",u6=p6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",jqa=p6("loadCastFramework")||p6("loadCastApplicationFramework"),Pqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(w6,g.H);g.h=w6.prototype;g.h.XC=function(a){this.o=arguments;this.g=!1;this.za?this.l=(0,g.D)()+this.Vc:this.za=g.Ig(this.u,this.Vc)};
g.h.stop=function(){this.za&&(g.w.clearTimeout(this.za),this.za=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.T=function(){this.stop();w6.Ha.T.call(this)};
g.h.YC=function(){this.l?(this.za=g.Ig(this.u,this.l-(0,g.D)()),this.l=null):(this.za=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};x6.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
x6.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=y6.prototype;g.h.Wg=null;g.h.we=!1;g.h.Si=null;g.h.Rs=null;g.h.Bi=null;g.h.Xh=null;g.h.jg=null;g.h.Bg=null;g.h.rh=null;g.h.tc=null;g.h.Sk=0;g.h.ze=null;g.h.fo=null;g.h.kg=null;g.h.Hj=-1;g.h.Lz=!0;g.h.Mg=!1;g.h.Lp=0;g.h.xn=null;var F6={},D6={};g.h=y6.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.FL=function(a){a=a.target;var b=this.xn;b&&3==L5(a)?b.Dj():this.TA(a)};
g.h.TA=function(a){try{if(a==this.tc)a:{var b=L5(this.tc),c=this.tc.u,d=this.tc.getStatus();if(g.Ld&&!g.nd(10)||g.Nd&&!g.md("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Dh&&!O5(this.tc))break a;this.Mg||4!=b||7==c||(8==c||0>=d?this.g.qe(3):this.g.qe(2));P6(this);var e=this.tc.getStatus();this.Hj=e;var f=O5(this.tc);(this.we=200==e)?(4==b&&H6(this),this.u?(J6(this,b,f),g.Dh&&this.we&&3==b&&(this.aa.da(this.i,"tick",this.BL),this.i.start())):G6(this,f),this.we&&!this.Mg&&(4==b?this.g.gn(this):(this.we=
!1,C6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.kg=3,E6(13)):(this.kg=0,E6(14)),H6(this),I6(this))}}catch(k){this.tc&&O5(this.tc)}finally{}};
g.h.BL=function(){var a=L5(this.tc),b=O5(this.tc);this.Sk<b.length&&(P6(this),J6(this,a,b),this.we&&4!=a&&C6(this))};
g.h.ZK=function(a){O6((0,g.y)(this.YK,this,a),0)};
g.h.YK=function(a){this.Mg||(P6(this),G6(this,a),C6(this))};
g.h.Ry=function(a){O6((0,g.y)(this.XK,this,a),0)};
g.h.XK=function(a){this.Mg||(H6(this),this.we=a,this.g.gn(this),this.g.qe(4))};
g.h.cancel=function(){this.Mg=!0;H6(this)};
g.h.jL=function(){this.Si=null;var a=(0,g.D)();0<=a-this.Rs?(2!=this.Xh&&this.g.qe(3),H6(this),this.kg=2,E6(18),I6(this)):N6(this,this.Rs-a)};
g.h.getLastError=function(){return this.kg};g.h=T6.prototype;g.h.Jp=null;g.h.Cd=null;g.h.yn=!1;g.h.Rv=null;g.h.Rl=null;g.h.zq=null;g.h.Kp=null;g.h.Zd=null;g.h.xf=-1;g.h.Gj=null;g.h.bj=null;g.h.connect=function(a){this.Kp=a;a=U6(this.g,null,this.Kp);E6(3);this.Rv=(0,g.D)();var b=this.g.D;null!=b?(this.Gj=b[0],(this.bj=b[1])?(this.Zd=1,V6(this)):(this.Zd=2,X6(this))):(E5(a,"MODE","init"),this.Cd=new y6(this,void 0,void 0,void 0),this.Cd.Wg=this.Jp,B6(this.Cd,a,!1,null,!0),this.Zd=0)};
g.h.jC=function(a){if(a)this.Zd=2,X6(this);else{E6(4);var b=this.g;b.He=b.Zf.xf;q7(b,9)}a&&this.qe(2)};
g.h.gp=function(a){return this.g.gp(a)};
g.h.abort=function(){this.Cd&&(this.Cd.cancel(),this.Cd=null);this.xf=-1};
g.h.Qv=function(){return!1};
g.h.Ly=function(a,b){this.xf=a.Hj;if(0==this.Zd)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.He=this.xf;q7(c,2);return}this.Gj=c[0];this.bj=c[1]}else c=this.g,c.He=this.xf,q7(c,2);else if(2==this.Zd)if(this.yn)E6(7),this.zq=(0,g.D)();else if("11111"==b){if(E6(6),this.yn=!0,this.Rl=(0,g.D)(),c=this.Rl-this.Rv,!g.Ld||g.nd(10)||500>c)this.xf=200,this.Cd.cancel(),E6(12),W6(this.g,this,!0)}else E6(8),this.Rl=this.zq=(0,g.D)(),this.yn=!1};
g.h.gn=function(){this.xf=this.Cd.Hj;if(this.Cd.we)0==this.Zd?this.bj?(this.Zd=1,V6(this)):(this.Zd=2,X6(this)):2==this.Zd&&((!g.Ld||g.nd(10)?!this.yn:200>this.zq-this.Rl)?(E6(11),W6(this.g,this,!1)):(E6(12),W6(this.g,this,!0)));else{0==this.Zd?E6(9):2==this.Zd&&E6(10);var a=this.g;this.Cd.getLastError();a.He=this.xf;q7(a,2)}};
g.h.Ik=function(){return this.g.Ik()};
g.h.isActive=function(){return this.g.isActive()};
g.h.qe=function(a){this.g.qe(a)};g.h=Y6.prototype;g.h.oj=null;g.h.yd=null;g.h.Qb=null;g.h.Ip=null;g.h.Tl=null;g.h.ju=null;g.h.gm=null;g.h.pk=0;g.h.kH=0;g.h.Tc=null;g.h.fg=null;g.h.kf=null;g.h.Rg=null;g.h.Zf=null;g.h.co=null;g.h.hi=-1;g.h.yw=-1;g.h.He=-1;g.h.Rh=0;g.h.Lh=0;g.h.Ng=8;var r7=new g.Sf;g.A(Z6,g.rf);g.A($6,g.rf);g.A(a7,g.rf);g.h=Y6.prototype;g.h.connect=function(a,b,c,d,e){E6(0);this.Ip=b;this.oj=c||{};d&&g.Ca(e)&&(this.oj.OSID=d,this.oj.OAID=e);this.A?(O6((0,g.y)(this.Bu,this,a),100),g7(this)):this.Bu(a)};
g.h.Bu=function(a){this.Zf=new T6(this);this.Zf.Jp=null;this.Zf.i=this.u;this.Zf.connect(a)};
g.h.Qv=function(){return 0==this.g};
g.h.Qy=function(a){this.fg=null;l7(this,a)};
g.h.Py=function(){this.kf=null;this.Qb=new y6(this,this.l,"rpc",this.B);this.Qb.Wg=null;this.Qb.Lp=0;var a=this.ju.clone();g.jn(a,"RID","rpc");g.jn(a,"SID",this.l);g.jn(a,"CI",this.co?"0":"1");g.jn(a,"AID",this.hi);c7(this,a);if(!g.Ld||g.nd(10))g.jn(a,"TYPE","xmlhttp"),B6(this.Qb,a,!0,this.gm,!1);else{g.jn(a,"TYPE","html");var b=this.Qb,c=!!this.gm;b.Xh=3;b.jg=D5(a.clone());M6(b,c)}};
g.h.Ly=function(a,b){if(0!=this.g&&(this.Qb==a||this.yd==a))if(this.He=a.Hj,this.yd==a&&3==this.g)if(7<this.Ng){try{var c=this.u.parse(b)}catch(f){c=null}if(g.Ka(c)&&3==c.length)if(0==c[0])a:{if(!this.kf){if(this.Qb)if(this.Qb.Bi+3E3<this.yd.Bi)h7(this),this.Qb.cancel(),this.Qb=null;else break a;o7(this);E6(19)}}else this.yw=c[1],0<this.yw-this.hi&&37500>c[2]&&this.co&&0==this.Lh&&!this.Rg&&(this.Rg=O6((0,g.y)(this.OH,this),6E3));else q7(this,11)}else b!=Ara.BN.g&&q7(this,11);else if(this.Qb==a&&
h7(this),!g.vb(b)){c=this.u.parse(b);g.Ka(c);for(var d=0;d<c.length;d++){var e=c[d];this.hi=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.gm=e[2],e=e[3],null!=e?this.Ng=e:this.Ng=6,this.g=3,this.Tc&&this.Tc.vu(),this.ju=U6(this,this.Ik()?this.gm:null,this.Ip),m7(this)):"stop"==e[0]&&q7(this,7):3==this.g&&("stop"==e[0]?q7(this,7):"noop"!=e[0]&&this.Tc&&this.Tc.uu(e),this.Lh=0)}}};
g.h.OH=function(){null!=this.Rg&&(this.Rg=null,this.Qb.cancel(),this.Qb=null,o7(this),E6(20))};
g.h.gn=function(a){if(this.Qb==a){h7(this);this.Qb=null;var b=2}else if(this.yd==a)this.yd=null,b=1;else return;this.He=a.Hj;if(0!=this.g)if(a.we)1==b?(b=(0,g.D)()-a.Bi,r7.dispatchEvent(new $6(r7,a.rh?a.rh.length:0,b,this.Rh)),f7(this),this.o.length=0):m7(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.He)){if(d=1==b)this.yd||this.fg||1==this.g||2<=this.Rh?d=!1:(this.fg=O6((0,g.y)(this.Qy,this,a),n7(this,this.Rh)),this.Rh++,d=!0);d=!(d||2==b&&o7(this))}if(d)switch(c){case 1:q7(this,
5);break;case 4:q7(this,10);break;case 3:q7(this,6);break;case 7:q7(this,12);break;default:q7(this,2)}}};
g.h.AC=function(a){if(!g.$a(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.jM=function(a){a?E6(2):(E6(1),p7(this,8))};
g.h.gp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new N5;a.R=!1;return a};
g.h.isActive=function(){return!!this.Tc&&this.Tc.isActive(this)};
g.h.qe=function(a){r7.dispatchEvent(new a7(r7,a))};
g.h.Ik=function(){return!(!g.Ld||g.nd(10))};
g.h=s7.prototype;g.h.vu=function(){};
g.h.uu=function(){};
g.h.tu=function(){};
g.h.Uo=function(){};
g.h.uv=function(){return{}};
g.h.isActive=function(){return!0};g.A(t7,g.H);g.h=t7.prototype;g.h.RK=function(){this.Vc=Math.min(3E5,2*this.Vc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Vc+15E3*Math.random();g.yo(this.g,a);this.i=(0,g.D)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Vc=5E3};g.A(u7,s7);g.h=u7.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Gf=function(a){return this.l.Xg(a)};
g.h.N=function(a,b){return this.l.N.apply(this.l,arguments)};
g.h.dispose=function(){this.Za||(this.Za=!0,g.pf(this.l),v7(this),g.pf(this.i),this.i=null)};
g.h.ea=function(){return this.Za};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new Y6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Tc=null);d.Tc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.hi):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.dc(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.B.push(c):w7(this)&&i7(this.g,c)};
g.h.vu=function(){this.i.reset();this.u=null;this.o=0;if(this.B.length){var a=this.B;this.B=[];for(var b=0,c=a.length;b<c;++b)i7(this.g,a[b])}this.N("handlerOpened")};
g.h.tu=function(a){var b=2==a&&401==this.g.He;4==a||b||this.i.start();this.N("handlerError",a)};
g.h.Uo=function(a){if(!this.i.isActive())this.N("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.B.push(d)}};
g.h.uv=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.dc(a,this.u);return a};
g.h.uu=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),e7(this.g)):this.N("handlerMessage",new nqa(a[0],a[1]))};
g.h.OL=function(){this.i.isActive();var a=this.g,b=0;a.Qb&&b++;a.yd&&b++;0==b&&this.connect(this.u,this.o)};x7.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
x7.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
x7.prototype.u=function(a){a(Error("request timed out"))};var tqa=(0,g.D)(),C7=null,G7=Array(50),F7=-1,H7=!1;g.A(I7,g.Q);I7.prototype.Id=function(){return this.g};
I7.prototype.contains=function(a){return!!c6(this.g,a)};
I7.prototype.get=function(a){return a?d6(this.g,a):null};
I7.prototype.info=function(a){E7(this.B,a)};g.A(K7,g.Q);var Bra=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=K7.prototype;g.h.start=function(){!this.g&&isNaN(this.za)&&this.WA()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.za)||(g.bq(this.za),this.za=NaN)};
g.h.T=function(){this.stop();K7.Ha.T.call(this)};
g.h.WA=function(){this.za=NaN;this.g=g.Xq(y7(this.A,"/pairing/get_screen"),{method:"POST",rb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.y)(this.FM,this),onError:(0,g.y)(this.EM,this),pd:(0,g.y)(this.GM,this)})};
g.h.FM=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.N("pairingComplete",new W5(c))};
g.h.EM=function(a){this.g=null;a.status&&404==a.status?this.i>=Bra.length?this.N("pairingFailed",Error("DIAL polling timed out")):(a=Bra[this.i],this.za=g.$p((0,g.y)(this.WA,this),a),this.i++):this.N("pairingFailed",Error("Server error "+a.status))};
g.h.GM=function(){this.g=null;this.N("pairingFailed",Error("Server not responding"))};g.A(M7,I7);g.h=M7.prototype;g.h.start=function(){L7(this)&&this.N("screenChange");!g.zt("yt-remote-lounge-token-expiration")&&wqa(this);g.bq(this.i);this.i=g.$p((0,g.y)(this.start,this),1E4)};
g.h.add=function(a,b){L7(this);J7(this,a);N7(this,!1);this.N("screenChange");b(a);a.token||wqa(this)};
g.h.remove=function(a,b){var c=L7(this);vqa(this,a)&&(N7(this,!1),c=!0);b(a);c&&this.N("screenChange")};
g.h.Yn=function(a,b,c,d){var e=L7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,N7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.N("screenChange")};
g.h.T=function(){g.bq(this.i);M7.Ha.T.call(this)};
g.h.iD=function(a){L7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}N7(this,!b);b&&E7(this.B,"Missed "+b+" lounge tokens.")};
g.h.hD=function(a){E7(this.B,"Requesting lounge tokens failed: "+a)};g.A(P7,g.Q);g.h=P7.prototype;g.h.start=function(){var a=parseInt(g.zt("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.D)()-144E5<a?0:a)?R7(this):(this.o=(0,g.D)()+3E5,g.xt("yt-remote-fast-check-period",this.o),this.Sr())};
g.h.isEmpty=function(){return g.Wb(this.g)};
g.h.update=function(){O7("Updating availability on schedule.");var a=this.A(),b=g.Kb(this.g,function(c,d){return c&&!!d6(a,d)},this);
Q7(this,b)};
g.h.T=function(){g.bq(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);P7.Ha.T.call(this)};
g.h.Sr=function(){g.bq(this.l);this.l=NaN;this.i&&this.i.abort();var a=zqa(this);if(Q5(a)){var b=y7(this.u,"/pairing/get_screen_availability");this.i=z7(this.u,b,{lounge_token:g.Qb(a).join(",")},(0,g.y)(this.vK,this,a),(0,g.y)(this.uK,this))}else Q7(this,{}),R7(this)};
g.h.vK=function(a,b){this.i=null;var c=g.Qb(zqa(this));if(g.qb(c,g.Qb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;Q7(this,d);R7(this)}else this.Jb("Changing Screen set during request."),this.Sr()};
g.h.uK=function(a){this.Jb("Screen availability failed: "+a);this.i=null;R7(this)};
g.h.Jb=function(a){E7("OnlineScreenService",a)};g.A(S7,I7);g.h=S7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.N("screenChange"),this.i.isEmpty()||this.N("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.Yn=function(a,b,c,d){this.l.contains(a)?this.l.Yn(a,b,c,d):(a="Updating name of unknown screen: "+a.name,E7(this.B,a),d(Error(a)))};
g.h.Id=function(a){return a?this.g:g.eb(this.g,(0,g.Xd)(this.o,function(b){return!this.contains(b)},this))};
g.h.XA=function(){return(0,g.Xd)(this.Id(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.YA=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new K7(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.y)(function(k){g.pf(f);d(T7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.pf(f);e(k)});
f.start();return(0,g.y)(f.stop,f)};
g.h.IM=function(a,b,c,d){g.Xq(y7(this.A,"/pairing/get_screen"),{method:"POST",rb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.y)(function(e,f){var k=new W5(f.screen||{});if(!k.name||Dqa(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);Dqa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(T7(this,k))},this),
onError:(0,g.y)(function(e){d(Error("pairing request failed: "+e.status))},this),
pd:(0,g.y)(function(){d(Error("pairing request timed out."))},this)})};
g.h.T=function(){g.pf(this.l);g.pf(this.i);S7.Ha.T.call(this)};
g.h.rD=function(){Eqa(this);this.N("screenChange");this.i.update()};
S7.prototype.dispose=S7.prototype.dispose;g.A(V7,g.Q);g.h=V7.prototype;g.h.hn=function(a){this.l=a;this.N("sessionScreen",this.l)};
g.h.Ld=function(a){this.ea()||(a&&W7(this,""+a),this.l=null,this.N("sessionScreen",null))};
g.h.info=function(a){E7(this.P,a)};
g.h.aB=function(){return null};
g.h.gs=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.y)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.y)(function(){W7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.T=function(){this.gs("");V7.Ha.T.call(this)};g.A(X7,V7);g.h=X7.prototype;g.h.es=function(a){if(this.g){if(this.g==a)return;W7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);Gqa(this)};
g.h.ji=function(a){this.info("launchWithParams no-op for Cast: "+g.Mg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.y)(function(){this.Ld()},this),(0,g.y)(function(){this.Ld(Error("Failed to stop receiver app."))},this)):this.Ld(Error("Stopping cast device witout session."))};
g.h.gs=g.Ga;g.h.T=function(){this.info("disposeInternal");g.bq(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;X7.Ha.T.call(this)};
g.h.vL=function(a,b){if(!this.ea())if(b){var c=S5(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Mg(c));switch(d){case "mdxSessionStatus":Fqa(this,c.screenId);break;default:W7(this,"Unknown youtube message: "+d)}}else W7(this,"Unable to parse message.")}else W7(this,"No data in message.")};
g.h.Jv=function(a,b,c,d){Cqa(this.F,this.i.label,a,this.i.friendlyName,(0,g.y)(function(e){e?b(e):0<=d?(W7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.$p((0,g.y)(this.Jv,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.aB=function(){return this.g};
g.h.JM=function(a){this.ea()||a||(W7(this,"Cast session died."),this.Ld())};g.A(Y7,V7);g.h=Y7.prototype;g.h.es=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.ji=function(a){this.u=a;this.B()};
g.h.stop=function(){this.g();this.g=g.Ga;g.bq(this.A);this.o?this.o.stop((0,g.y)(this.Ld,this,null),(0,g.y)(this.Ld,this,"Failed to stop DIAL device.")):this.Ld()};
g.h.T=function(){this.g();this.g=g.Ga;g.bq(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;Y7.Ha.T.call(this)};
g.h.MM=function(a){this.ea()||a||(W7(this,"DIAL session died."),this.g(),this.g=g.Ga,this.Ld())};
g.h.Yp=function(a){this.H=b6();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,Iqa(this));a(b);Hqa(this)}else this.B=(0,g.y)(function(){g.bq(this.A);this.B=g.Ga;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,Iqa(this));a(c);Hqa(this)},this),this.A=g.$p((0,g.y)(function(){this.B()},this),100)};
g.h.OD=function(a,b,c){Cqa(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.y)(function(d){d&&d.token?(this.hn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Yp(b,c)},this),(0,g.y)(function(d){W7(this,"Failed to get DIAL screen: "+d);
this.Yp(b,c)},this))};g.A(Z7,V7);Z7.prototype.stop=function(){this.Ld()};
Z7.prototype.es=g.Ga;Z7.prototype.ji=function(){g.bq(this.g);this.g=NaN;var a=d6(this.F.Id(),this.i.label);a?this.hn(a):this.Ld(Error("No such screen"))};
Z7.prototype.T=function(){g.bq(this.g);this.g=NaN;Z7.Ha.T.call(this)};g.A($7,g.Q);g.h=$7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.B);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.y)(this.Ny,this),(0,g.y)(this.eK,this),d,e);c.customDialLaunchCallback=(0,g.y)(this.oI,this);chrome.cast.initialize(c,(0,g.y)(function(){this.ea()||
(chrome.cast.addReceiverActionListener(this.o),qqa(),this.i.subscribe("onlineScreenChange",(0,g.y)(this.ZA,this)),this.l=Kqa(this),chrome.cast.setCustomReceivers(this.l,g.Ga,(0,g.y)(function(f){this.Jb("Failed to set initial custom receivers: "+g.Mg(f))},this)),this.N("yt-remote-cast2-availability-change",b8(this)),b(!0))},this),(0,g.y)(function(f){this.Jb("Failed to initialize API: "+g.Mg(f));
b(!1)},this))};
g.h.XL=function(a,b){a8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)a8("Unsetting old screen status: "+this.g.i.friendlyName),c8(this,null)}if(a&&b){if(!this.g){c=d6(this.i.Id(),a);if(!c){a8("setConnectedScreenStatus: Unknown screen.");return}var d=Jqa(this,c);d||(a8("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ga,(0,g.y)(function(e){this.Jb("Failed to set initial custom receivers: "+g.Mg(e))},this)));
a8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);c8(this,new Z7(this.i,d),!0)}this.g.gs(b)}else a8("setConnectedScreenStatus: no screen.")};
g.h.YL=function(a){this.ea()?this.Jb("Setting connection data on disposed cast v2"):this.g?this.g.ji(a):this.Jb("Setting connection data without a session")};
g.h.LM=function(){this.ea()?this.Jb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),c8(this,null)):a8("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.y)(this.Ny,this),(0,g.y)(this.AK,this))};
g.h.T=function(){this.i.unsubscribe("onlineScreenChange",(0,g.y)(this.ZA,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.cb(g.x("yt.mdx.remote.debug.handlers_")||[],A7);g.pf(this.g);$7.Ha.T.call(this)};
g.h.Jb=function(a){E7("Controller",a)};
g.h.Oy=function(a,b){this.g==a&&(b||c8(this,null),this.N("yt-remote-cast2-session-change",b))};
g.h.aK=function(a,b){if(!this.ea())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),a8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)a8("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{a8("onReceiverAction_: Casting to active receiver.");this.g.l&&this.N("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:c8(this,
new Z7(this.i,a));break;case chrome.cast.ReceiverType.DIAL:c8(this,new Y7(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:c8(this,new X7(this.i,a));break;default:this.Jb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Jb("Stopping receiver w/o session: "+a.friendlyName)}else this.Jb("onReceiverAction_ called without receiver.")};
g.h.oI=function(a){if(this.ea())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Jb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Jb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return a8("Reselecting dial screen."),
this.N("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Jb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);c8(this,new Y7(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.y)(b.OD,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.y)(b.Yp,b))};
g.h.Ny=function(a){if(!this.ea()){a8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)a8("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),c8(this,new X7(this.i,b),!0);else{this.Jb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=d6(this.i.Id(),c.label);d&&X5(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(a8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.pf(this.g),this.g=new X7(this.i,b),this.g.subscribe("sessionScreen",(0,g.y)(this.Oy,this,this.g)),this.g.ji(null));this.g.es(a)}}};
g.h.KM=function(){return this.g?this.g.aB():null};
g.h.AK=function(a){this.ea()||(this.Jb("Failed to estabilish a session: "+g.Mg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&c8(this,null))};
g.h.eK=function(a){a8("Receiver availability updated: "+a);if(!this.ea()){var b=b8(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;b8(this)!=b&&this.N("yt-remote-cast2-availability-change",b8(this))}};
g.h.ZA=function(){this.ea()||(this.l=Kqa(this),a8("Updating custom receivers: "+g.Mg(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ga,(0,g.y)(function(){this.Jb("Failed to set custom receivers.")},this)),this.N("yt-remote-cast2-availability-change",b8(this)))};
$7.prototype.setLaunchParams=$7.prototype.YL;$7.prototype.setConnectedScreenStatus=$7.prototype.XL;$7.prototype.stopSession=$7.prototype.LM;$7.prototype.getCastSession=$7.prototype.KM;$7.prototype.requestSession=$7.prototype.requestSession;$7.prototype.init=$7.prototype.init;$7.prototype.dispose=$7.prototype.dispose;var i8=[];n8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";o8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Je=a.hasPrevious,this.hasNext=a.hasNext,this.B=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
n8.prototype.isAdPlaying=function(){return 1081==this.playerState};
n8.prototype.getDuration=function(){return this.u?this.D+p8(this):this.D};
n8.prototype.clone=function(){return new n8(t8(this))};g.A(v8,g.Q);g.h=v8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ga,B8(this,"play")):A8(this,"play"),z8(this,1,r8(w8(this))),this.N("remotePlayerChange")):x8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ga,B8(this,"pause")):A8(this,"pause"),z8(this,2,r8(w8(this))),this.N("remotePlayerChange")):x8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=w8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ga,B8(this,"seekTo",{newTime:a}))}else A8(this,"seekTo",{newTime:a});z8(this,3,a);this.N("remotePlayerChange")}else x8(this,g.Qa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ga,B8(this,"stopVideo")):A8(this,"stopVideo");var a=w8(this);a.index=-1;a.videoId="";o8(a);y8(this,a);this.N("remotePlayerChange")}else x8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=w8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.y)(function(){E7("CP","set receiver volume: "+d)},this),(0,g.y)(function(){this.Jb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.y)(function(){E7("CP","set receiver muted: "+b)},this),(0,g.y)(function(){this.Jb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);A8(this,"setVolume",e)}c.muted=b;c.volume=a;y8(this,c)}else x8(this,g.Qa(this.setVolume,a,b))};
g.h.Zz=function(a,b){if(1==this.g){var c=w8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Mg(b.style),g.dc(d,c.g));A8(this,"setSubtitlesTrack",d);y8(this,c)}else x8(this,g.Qa(this.Zz,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();A8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=w8(this);d.audioTrackId=c;y8(this,d)}else x8(this,g.Qa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=w8(this);c=c||0;var m={videoId:a,currentIndex:c};s8(l,a,c);g.Ca(b)&&(q8(l,b),m.currentTime=b);g.Ca(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Mg(k));A8(this,"setPlaylist",m);d||y8(this,l)};
g.h.tn=function(a,b){if(1==this.g){if(a&&b){var c=w8(this);s8(c,a,b);y8(this,c)}A8(this,"previous")}else x8(this,g.Qa(this.tn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=w8(this);s8(c,a,b);y8(this,c)}A8(this,"next")}else x8(this,g.Qa(this.nextVideo,a,b))};
g.h.Uu=function(){1==this.g?A8(this,"dismissAutoplay"):x8(this,this.Uu)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.N("proxyStateChange",a,this.g)}v8.Ha.dispose.call(this)};
g.h.T=function(){Xqa(this);this.o=null;this.u.clear();u8(this,null);v8.Ha.T.call(this)};
g.h.Us=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.N("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.XJ=function(a,b){this.N(a,b)};
g.h.UH=function(a){if(!a)this.rk(null),u8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=w8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)E7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,y8(this,b)}};
g.h.rk=function(a){E7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),Yqa(this),this.N("remotePlayerChange")};
g.h.TH=function(a){a?(Yqa(this),this.N("remotePlayerChange")):this.rk(null)};
g.h.Es=function(){A8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.gI=function(){var a=Uqa();a&&u8(this,a)};
g.h.Jb=function(a){E7("CP",a)};g.A(C8,g.Q);g.h=C8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ca(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ca(k)&&(l.currentIndex=k);c&&(this.Qa.listId=c);this.Qa.videoId=d;this.Qa.index=k||0;this.Qa.state=3;q8(this.Qa,m);this.o="UNSUPPORTED";D8("Connecting with setPlaylist and params: "+g.Mg(l));this.g.connect({method:"setPlaylist",
params:g.Mg(l)},a,j6())}else D8("Connecting without params"),this.g.connect({},a,j6());$qa(this)};
g.h.dispose=function(){this.ea()||(this.N("beforeDispose"),E8(this,3));C8.Ha.dispose.call(this)};
g.h.T=function(){F8(this);H8(this);G8(this);g.bq(this.F);this.F=NaN;g.bq(this.H);this.H=NaN;this.l=null;g.es(this.O);this.O.length=0;this.g.dispose();C8.Ha.T.call(this);this.o=this.B=this.i=this.Qa=this.g=null};
g.h.bD=function(){this.A(2)};
g.h.YH=function(){D8("Channel opened");this.M&&(this.M=!1,G8(this),this.P=g.$p((0,g.y)(function(){D8("Timing out waiting for a screen.");this.A(1)},this),15E3));
hqa(oqa(this.g),this.V)};
g.h.VH=function(){D8("Channel closed");isNaN(this.u)?m6(!0):m6();this.dispose()};
g.h.WH=function(a){m6();isNaN(this.D())?(D8("Channel error: "+a+" without reconnection"),this.dispose()):(this.M=!0,D8("Channel error: "+a+" with reconnection in "+this.D()+" ms"),E8(this,2))};
g.h.XH=function(a){a.params?D8("Received: action="+a.action+", params="+g.Mg(a.params)):D8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=S5(a.params.devices);this.i=(0,g.G)(a,function(c){return new V5(c)});
a=!!g.Xa(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
cra(this,a);break;case "loungeScreenDisconnected":g.db(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
cra(this,!1);break;case "remoteConnected":var b=new V5(S5(a.params.device));g.Xa(this.i,function(c){return b?c.id==b.id:!1})||Wpa(this.i,b);
break;case "remoteDisconnected":b=new V5(S5(a.params.device));g.db(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":era(this,a);break;case "nowPlaying":gra(this,a);break;case "onStateChange":fra(this,a);break;case "onAdStateChange":hra(this,a);break;case "onVolumeChanged":ira(this,a);break;case "onSubtitlesTrackChanged":dra(this,a);break;case "nowAutoplaying":jra(this,a);break;case "autoplayDismissed":this.N("autoplayDismissed");break;case "autoplayUpNext":this.B=a.params.videoId||null;this.N("autoplayUpNext",this.B);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.N("autoplayModeChange",this.o);"DISABLED"==this.o&&this.N("autoplayDismissed");break;case "onHasPreviousNextChanged":kra(this,a);break;case "requestAssistedSignIn":this.N("assistedSignInRequested",a.params.authCode);break;default:D8("Unrecognized action: "+a.action)}};
g.h.LL=function(){if(this.l){var a=this.l;this.l=null;this.Qa.videoId!=a&&I8(this,"getNowPlaying")}};
C8.prototype.subscribe=C8.prototype.subscribe;C8.prototype.unsubscribeByKey=C8.prototype.Gf;C8.prototype.ca=function(){var a=3;this.ea()||(a=0,isNaN(this.D())?w7(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
C8.prototype.getProxyState=C8.prototype.ca;C8.prototype.A=function(a){D8("Disconnecting with "+a);F8(this);this.N("beforeDisconnect",a);1==a&&m6();v7(this.g,a);this.dispose()};
C8.prototype.disconnect=C8.prototype.A;C8.prototype.X=function(){var a=this.Qa;this.l&&(a=this.Qa.clone(),s8(a,this.l,a.index));return t8(a)};
C8.prototype.getPlayerContextData=C8.prototype.X;
C8.prototype.ka=function(a){var b=new n8(a);b.videoId&&b.videoId!=this.Qa.videoId&&(this.l=b.videoId,g.bq(this.F),this.F=g.$p((0,g.y)(this.LL,this),5E3));var c=[];this.Qa.listId==b.listId&&this.Qa.videoId==b.videoId&&this.Qa.index==b.index||c.push("remoteQueueChange");this.Qa.playerState==b.playerState&&this.Qa.volume==b.volume&&this.Qa.muted==b.muted&&r8(this.Qa)==r8(b)&&g.Mg(this.Qa.g)==g.Mg(b.g)||c.push("remotePlayerChange");this.Qa.reset(a);(0,g.B)(c,function(d){this.N(d)},this)};
C8.prototype.setPlayerContextData=C8.prototype.ka;C8.prototype.R=function(){var a=this.g.A.id,b=g.Xa(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
C8.prototype.getOtherConnectedRemoteId=C8.prototype.R;C8.prototype.D=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.D)():NaN};
C8.prototype.getReconnectTimeout=C8.prototype.D;C8.prototype.ba=function(){return this.o||"UNSUPPORTED"};
C8.prototype.getAutoplayMode=C8.prototype.ba;C8.prototype.Z=function(){return this.B||""};
C8.prototype.getAutoplayVideoId=C8.prototype.Z;C8.prototype.va=function(){if(!isNaN(this.D())){var a=this.g.i;g.zo(a.g);a.start()}};
C8.prototype.reconnect=C8.prototype.va;C8.prototype.ia=function(a,b){I8(this,a,b);bra(this)};
C8.prototype.sendMessage=C8.prototype.ia;g.A(J8,I7);g.h=J8.prototype;g.h.Id=function(a){return this.Hc.$_gs(a)};
g.h.contains=function(a){return!!this.Hc.$_c(a)};
g.h.get=function(a){return this.Hc.$_g(a)};
g.h.start=function(){this.Hc.$_st()};
g.h.add=function(a,b,c){this.Hc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Hc.$_r(a,b,c)};
g.h.Yn=function(a,b,c,d){this.Hc.$_un(a,b,c,d)};
g.h.T=function(){for(var a=0,b=this.i.length;a<b;++a)this.Hc.$_ubk(this.i[a]);this.i.length=0;this.Hc=null;J8.Ha.T.call(this)};
g.h.HM=function(){this.N("screenChange")};
g.h.BJ=function(){this.N("onlineScreenChange")};
S7.prototype.$_st=S7.prototype.start;S7.prototype.$_gspc=S7.prototype.IM;S7.prototype.$_gsppc=S7.prototype.YA;S7.prototype.$_c=S7.prototype.contains;S7.prototype.$_g=S7.prototype.get;S7.prototype.$_a=S7.prototype.add;S7.prototype.$_un=S7.prototype.Yn;S7.prototype.$_r=S7.prototype.remove;S7.prototype.$_gs=S7.prototype.Id;S7.prototype.$_gos=S7.prototype.XA;S7.prototype.$_s=S7.prototype.subscribe;S7.prototype.$_ubk=S7.prototype.Gf;var K8=null,L8=null,$8=null,P8=[];g.t(a9,g.H);g.h=a9.prototype;
g.h.T=function(){g.H.prototype.T.call(this);this.o.stop();this.A.stop();this.I.stop();this.M();this.g.unsubscribe("proxyStateChange",this.Ky,this);this.g.unsubscribe("remotePlayerChange",this.uk,this);this.g.unsubscribe("remoteQueueChange",this.jn,this);this.g.unsubscribe("autoplayUpNext",this.ly,this);this.g.unsubscribe("previousNextChange",this.Hy,this);this.g.unsubscribe("nowAutoplaying",this.Dy,this);this.g.unsubscribe("autoplayDismissed",this.ky,this);this.g=this.u=null};
g.h.kx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(d9(this)){if(!w8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==w8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Dj(c[0],c[1]);break;case "control_subtitles_set_track":e9(this,c[0]);break;case "control_set_audio_track":c=c[0],d9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();f9(this,0==c?void 0:c);break;case "control_seek":f9(this,c[0]);break;case "control_subtitles_set_track":e9(this,c[0]);break;case "control_set_audio_track":c=c[0],d9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.SH=function(a){this.I.XC(a)};
g.h.rM=function(a){this.kx("control_subtitles_set_track",g.Wb(a)?null:a)};
g.h.lA=function(){var a=this.i.getOption("captions","track");g.Wb(a)||e9(this,a)};
g.h.zy=function(a){if(d9(this)){this.g.unsubscribe("remotePlayerChange",this.uk,this);var b=Math.round(a.volume);a=!!a.muted;var c=w8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.P.start();this.g.subscribe("remotePlayerChange",this.uk,this)}};
g.h.TI=function(){g.Wb(this.B)||wra(this,this.B);this.D=!1};
g.h.Ky=function(a,b){this.A.stop();2==b&&this.kA()};
g.h.uk=function(){if(d9(this)){this.o.stop();var a=w8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.ym=1;break;case 1082:case 1083:this.u.ym=0;break;default:this.u.ym=-1}switch(a.playerState){case 1081:case 1:c9(this,new g.zC(8));this.jA();break;case 1085:case 3:c9(this,new g.zC(9));break;case 1083:case 0:c9(this,new g.zC(2));this.H.stop();b9(this,this.i.getVideoData().lengthSeconds);break;case 1084:c9(this,new g.zC(4));break;case 2:c9(this,new g.zC(4));b9(this,r8(a));
break;case -1:c9(this,new g.zC(64));break;case -1E3:c9(this,new g.zC(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=w8(this.g).g;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,wra(this,a));a=w8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.P.isActive()||this.KA()}else vra(this)};
g.h.Hy=function(){this.i.N("mdxpreviousnextchange")};
g.h.jn=function(){d9(this)||vra(this)};
g.h.iC=function(){this.g.Uu()};
g.h.ly=function(a){a&&(a=g.Xq("/watch_queue_ajax",{method:"GET",Ec:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.y)(this.cL,this)}))&&(this.M=(0,g.y)(a.abort,a))};
g.h.cL=function(a,b){var c=new g.kB(g.X(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.N("mdxautoplayupnext",c)};
g.h.Dy=function(a){isNaN(a)||this.i.N("mdxnowautoplaying",a)};
g.h.ky=function(){this.i.N("mdxautoplaycanceled")};
g.h.yF=function(a,b){-1==w8(this.g).playerState?f9(this,a):b&&this.g.seekTo(a)};
g.h.KA=function(){if(d9(this)){var a=w8(this.g);this.l.Ma(this.O);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.O=this.l.K(this.i,"onVolumeChange",this.zy)}};
g.h.jA=function(){this.o.stop();if(!this.g.ea()){var a=w8(this.g);1==a.playerState&&c9(this,new g.zC(8));b9(this,r8(a));this.o.start()}};
g.h.kA=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(g9,g.W);g9.prototype.u=function(a){yra(this,a.state)};g.t(h9,g.ZT);h9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.F=g.sb(a,this.A,this),g.$T(this,(0,g.G)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.pe(this.A(a)),this.enable(!0)):this.enable(!1)};
h9.prototype.A=function(a){return a.key};
h9.prototype.oe=function(a){return"cast-selector-receiver"==a?"Cast...":this.F[a].name};
h9.prototype.Jc=function(a){g.ZT.prototype.Jc.call(this,a);this.l.setOption("remote","currentReceiver",this.F[a]);this.o.gb()};g.t(i9,g.UK);g.h=i9.prototype;g.h.create=function(){pra(g.cz(g.X(this.player)));this.u.push(g.gq("yt-remote-before-disconnect",this.PH,this));this.u.push(g.gq("yt-remote-connection-change",this.fK,this));this.u.push(g.gq("yt-remote-receiver-availability-change",this.Iy,this));this.u.push(g.gq("yt-remote-auto-connect",this.dK,this));this.u.push(g.gq("yt-remote-receiver-resumed",this.cK,this));this.Iy()};
g.h.load=function(){this.player.cancelPlayback();g.UK.prototype.load.call(this);this.o=new a9(this,this.player,this.g);var a=(a=ura())?a.currentTime:0;var b=Z8()?new v8(U8(),void 0):null;0==a&&b&&(a=r8(w8(b)));0!=a&&this.qd(a);xra(this,this.ck,this.ck);g.YX(this.player.app,6)};
g.h.unload=function(){this.player.N("mdxautoplaycanceled");this.l=this.i;g.qf(this.o,this.g);this.g=this.o=null;g.UK.prototype.unload.call(this);g.YX(this.player.app,5)};
g.h.T=function(){g.hq(this.u);g.UK.prototype.T.call(this)};
g.h.Ue=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.o.kx.apply(this.o,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.ym};
g.h.TC=function(){return this.loaded?this.o.suggestion:null};
g.h.Je=function(){return this.g?w8(this.g).Je:!1};
g.h.hasNext=function(){return this.g?w8(this.g).hasNext:!1};
g.h.qd=function(a,b){this.D=a||0;this.player.N("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.D};
g.h.getProgressState=function(){var a=w8(this.g),b=this.player.getVideoData();return{allowSeeking:g.R(g.X(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.ec():!a.isAdPlaying()&&this.player.ec(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+p8(a):a.l,isAtLiveHead:1>=(a.u?a.i+p8(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+p8(a):a.i,seekableStart:0<a.o?a.o+
p8(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.tn=function(){this.g&&this.g.tn()};
g.h.PH=function(a){1==a&&(this.B=this.g?w8(this.g):null)};
g.h.fK=function(){var a=Z8()?new v8(U8(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.B=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.pf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.B)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,r8(a)));this.player.N("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Iy=function(){this.A=[this.i].concat(rra());var a=V8()||this.i;j9(this,a);this.player.ma("onMdxReceiversChange")};
g.h.dK=function(){var a=V8();j9(this,a)};
g.h.cK=function(){this.l=V8()};
g.h.Zb=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.A;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?l8():j9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.A.length&&"cast-selector-receiver"==this.A[1].key?(b&&l8(),!0):!1}};
g.h.Es=function(){this.g.Es()};
g.h.Mb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.oV.remote=i9;})(_yt_player);
